### ISSUE TITLE
[Telemetry] V1 Telemetry Foundation

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#101]
# Objective
Build a foudnation for Pocket V1 Telemetry with a couple use-cases.

# Origin Document

We are interested in gaining insight into the application correctness of pocket nodes, thus we want to introduce telemetry to the v1 codebase to monitor the performance and behaviour of both RainTree and HotPOKT as a starting pointing and develop more as we go forward.

![68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3936353938383735393534353938333034372f3937343339383732383530373130353331302f6469616772616d732e6a70673f77696474683d31393430266865696768743d31343535](https://user-images.githubusercontent.com/1892194/176556384-95fc2403-cdb1-480d-bde1-70fa1017929a.jpeg)

# Goals
## Deliverables
- [ ] (1) Telemtry infrastructure
- [ ] (2) Telemtry module foundation
- [ ] (3) V1 Metrics - RainTree: verify correctness of p2p implementation
- [ ] (4) V1 Metrics - HotPOKT: verify correctness of consensus implementation
- [ ] V1 Logs - Modules: togglable and filterable)
- [ ] V1 Logs - Levels: togglable and filterable)

## Testing Methodology
How to properly test this issue

## Non-goals
- List of goals that this issue won't address

Owner: @derrandz 
Co-Owners: @okdas @Olshansk

**Comment by derrandz** [comment]
Merging #135 Ticks off deliverables (1, 2, 3, 4). The remaining deliverables will be addressed in a separate PR.

**Comment by Olshansk** [comment]
The foundation for telemetry has been merged into main so closing this out.
