### ISSUE TITLE
[Persistence] Consolidate common behaviour between `Pool` and `Account` into a shared interface

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#102]
# Objective
Remove redundant code used by the `Pool` and `Account` actors in the persistence module introduced in https://github.com/pokt-network/pocket/pull/73.

This is a good starter task opportunity to get acquainted with the codebase in the persistence module.

# Origin Document

From the [utility specification[https://github.com/pokt-network/pocket-network-protocol/tree/main/utility), a `Pool` is described as:
```
	A ModulePool is a particular type that though similar in structure to an Account, the
	functionality of each is quite specialized to its use case. These pools are maintained by
	the protocol and are completely autonomous, owned by no actor on the network. Unlike Accounts,
	tokens are able to be directly minted to and burned from ModulePools. Examples of ModuleAccounts
	include StakingPools and the FeeCollector
```			

Similar to how the functionality of Fisherman, ServiceNode, Validator and Application was consolidated via `persistence/schema/protocol_actor.go` and `persistence/schema/base_actor.go`, the functionality of Pool and Account can also be shared to remove redundant code.

# Goals
## Deliverables
- [ ] Extract common functionality of `Pool` and `Account` into a common interface
- [ ] At a minimum, the following files will need to be affected: `persistence/schema/account.go`, `persistence/account.go`, `persistence/test/account_test.go`

## Testing Methodology
- [ ] ` $ make test_persistence`
- [ ] ` $ make test_all`
- [ ] Run a `LocalNet` following the instructions in `docs/development/README.md`

## Non-goals
- Adding new functionality to the persistence module

Creator: @Olshansk 
Owner: @DragonDmoney
Co-Owners: @andrewnguyen22

**Comment by DragonDmoney** [comment]
Note: I am currently working on this.

**Comment by Olshansk** [comment]
@DragonDmoney Do you think this is something you can have up for review by the end of the month?

**Comment by andrewnguyen22** [comment]
Somewhat tackled in #154 by merging the two structures in protobuf. Will leave the rest to #163

**Comment by Olshansk** [comment]
Spoke to @DragonDmoney offline and he mentioned he won't be working on this any longer.

**Comment by h5law** [comment]
@Olshansk I would like to take a swing at this issue if its still relevant? I have working code that passes tests ready to submit a PR if its still applicable?

**Comment by Olshansk** [comment]
> @Olshansk I would like to take a swing at this issue if its still relevant? I have working code that passes tests ready to submit a PR if its still applicable?

Still applicable, let's do it!
