### ISSUE TITLE
[Consensus] HotPOKT Validator Signature Aggregation

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#107]
# Objective

Replace the use of Ed25519 in the first iteration of HotPOKT which uses lists of signatures for block proposals and voting with BLS signatures. This will be closer to the theoretical design of a Hotstuff-based consensus mechanism.

# Origin Document
The Pocket protocol consensus specification can be found [here](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility).

The current consensus interface can be found [here](https://github.com/pokt-network/pocket/tree/main/consensus) with the shared interface available [here](https://github.com/pokt-network/pocket/blob/main/shared/modules/c[onsensus](https://github.com/pokt-network/pocket/blob/main/shared/modules/utility_module.go)_module.go).

During our initial research, we found out that k-of-n threshold signature mechanisms are still relatively early from both a design and implementation perspective, but feasible later in the R&D cycle. This aims to prepare us for the next milestone.

# Goals / Deliverables
- [ ] Replace the Ed25519 asymmetric key mechanism with BLS for validator signature aggregation
- [ ] Design modules/interfaces/libraries that prepare the codebase for both DKG and k-of-n threshold signing mechanisms in the future
- [ ] Replace round-robin leader election by leveraging the existing VRF and cryptographic sortition algorithm for leader election
- [ ] Testing
     - [ ] Add unit tests where appropriate 
     - [ ] Determine the viability of implementing the “Twins: BFT Systems Made Robust” test
         - [ ] Implement it if viable at this stage
- Documentation
    - [ ] Update the module-specific CHANGELOG
    - [ ] Update the module-specific README
    - [ ] Update the global documentation & references
    - [ ] Add details on how to run/test/debug the new functionality
    - [ ] A state diagram documenting the interaction between different components / libraries / interfaces
    - [ ] If possible: a sequence diagram of the functionality added
 - Identify future work
    - [ ] Document small issues / TODOs in the code for future work
    - [ ] Document which parts of the spec are implemented and which are mocked to track “spec coverage”     

##  Testing Methodology
LocalNet and Unit Tests. See [./docs/development/README.md](docs/development/README.md) for more details.

## Non-goals
- Implement a DKG mechanism
- Implement a threshold signature mechanism
- Modifications to the existing spec

Owners:  @Olshansk

**Comment by andrewnguyen22** [comment]
Closing in favor of #109

**Comment by Olshansk** [comment]
This was an "integration" issue associated with the milestone, but we're not doing that anymore.
