### ISSUE TITLE
[Telemetry/Observability] Standardize metrics and logs

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#118]
# Objective
Provide a way to monitor process and investigate issues for local deployments

# Origin Document
N/A

# Goals / Deliverables
- [ ]  Investigate [https://opentelemetry.io/](https://opentelemetry.io/) if existing SDKs are a good fit
- [x]  add golang process metrics (covered to some extent by #95)
- [ ]  add app specific metrics (blockchain height, msg_ counts, etc.)
    - [ ]  Only data necessary for monitoring/high-level observability ([[why](https://www.robustperception.io/cardinality-is-key/)](https://www.robustperception.io/cardinality-is-key/))
- [ ]  logs: standardize output for easier, predictable queries / shared namespace with metrics
    - [ ]  json/text
    - [ ]  (?) include module/namespace in logs
- [ ]  Modify Grafana dashboards for easier local development
    - [ ]  High level, all processes
    - [ ]  High level, one process with logs
    - [ ]  Low level, one process with deep metrics

## General milestone checklist
- [ ] Update all the relevant CHANGELOGs
- [ ] Update all the relevant READMEs
- [ ] Update the source code tree explanation
- [ ] Add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Create followup milestones + issues
- [ ] Document small TODO along the way

# Non-goals
- Full compliance with OpenTelemetry standard

---

Creator: @okdas 
Co-Owners: TBD

**Comment by Olshansk** [comment]
@okdas Can you attach this to a milestone?

**Comment by Olshansk** [comment]
@okdas Could you review and either close or decompose this issue given the other tasks in the M2 milestone?
