### ISSUE TITLE
[UX] `make protogen_clean` fails if there are no generated files

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#129]
# Objective

Improve Developer UX

# Origin Document

Currently, when following the [guidelines](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md#prepare-local-environment) for preparing a local environment, the user is faced with an error

![image](https://user-images.githubusercontent.com/29378614/181459284-69776f68-baf9-4e19-807b-28d58075cf55.png)

# Goals / Deliverables
- [ ] Make sure that by following the instructions, the developer experience is as smooth as possible.

## General issue checklist
- [ ] Fix `protogen_clean` so that it doesn't throw errors when getting started

# Non-goals

N/A

# Testing Methodology
- `make protogen_clean` 

---

Creator: @deblasis
Co-Owners: [optional - github usernames of the co-owner(s)]

**Comment by Olshansk** [comment]
Per my comment in https://github.com/pokt-network/pocket/issues/131, ty!
