### ISSUE TITLE
[UX] several `Makefile` commands fail because of `builtin` 

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#131]
# Objective

Improve Developer UX

# Origin Document

When following the instructions for [running LocalNet](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md#running-localnet) 

the user might encounters the error: 

![image](https://user-images.githubusercontent.com/29378614/181471594-2ebf2842-7dd0-4c2f-b81e-11abf2c7ef85.png)

in some shell environments (tested using `zsh` on Ubuntu 20.04 on WSL2 🥴)

This is due to the usage of `builtin` for testing if dependencies (`docker`, `docker-compose`, etc) are installed.
`builtin` is provided by `/bin/bash` for backward compatibility, `command` replaces it

![image](https://user-images.githubusercontent.com/29378614/181472712-9d59c804-25bd-4923-9a2d-ae1a30fb7c33.png)
[source](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html#tag_20_22_18)

This issue could be solved by either:
- replacing each and every instance of `builtin` with a check done via `command` or `which`
- adding a `SHELL := /bin/bash` at the top of the `Makefile` in order to coerce the shell to Bash

I personally lean towards using "standards" versus stuff that sooner rather than later is going to be deprecated, especially if we are already using something that's there for backward compatibility, so I'd use `command` instead

# Goals / Deliverables
- [ ] Improve UX

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

# Non-goals
- *List of tasks / goals this issue SHOULD NOT address since they are out of scope*
- ...

# [Optional] Testing Methodology
- **make compose_and_watch** should not fail 

---

Creator: @deblasis
Co-Owners: [optional - github usernames of the co-owner(s)]

**Comment by Olshansk** [comment]
Thank you @deblasis! Really appreciate these small tooling/documentation edits that everyone is going to hit as more people are onboarded.
