### ISSUE TITLE
[Utility] Create State Object in place of GenesisState

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#136]
# Objective
Convert GenesisState and GenesisActor into State{} and Actor{}

# Origin Document
Currently we have 'genesis actors' and 'genesis state', but in reality this object reflects the state in its entirety. For clarity and ease of understanding, we should maintain a State{} object that is shared among the persistence and utility module.

# Goals / Deliverables
- [ ] Code complete dellivery
- [ ] Specification document that reflects the current State{} object

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

---

Creator: @andrewnguyen22 
Co-Owners: @Olshansk

**Comment by Olshansk** [comment]
@andrewnguyen22 Could you provide more details on what you had envisioned here? Perhaps an example struct or interface?

Seems like exposing it via the app-specific bus would be sufficient?

**Comment by andrewnguyen22** [comment]
closed with #154
