### ISSUE TITLE
[Infrastructure] K8s operator initiative kickoff

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#145]
# Objective
We are exploring idea of developing a Kubernetes Operator to manage v1 Pocket Nodes as an alternative to using Helm/jsonnet/kustomize along with CD operator.

# Origin Document
https://www.notion.so/pocketnetwork/K8s-Operator-kickstart-8c61feb06e1949d5bc1d9f4d5548449d

# Goals / Deliverables
- [ ] Need to kickstart an operator in a separate repo (we will create one)
- [ ] Must support different actors 
- [ ] Support for different networks (devnets/testnets/mainnets/etc)
- [ ] TBD - Spec WIP

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

# Non-goals
-  To have a complete Operator ready for v1 mainnet
- ...

---

Creator: @okdas 
Co-Owners: @vlad-she @Gustavobelfort @lander2k2

**Comment by Olshansk** [comment]
@okdas Could you link to the repo or any other resources/details that's tracking work for this?

**Comment by Olshansk** [comment]
For reference, the demo video can be found here: https://www.youtube.com/watch?v=Tf9Qtr1gi3U

Links to the relevant repos and WIP is:
* v1 Pocket Operator (work in progress): [https://github.com/pokt-network/operator](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbl9OcDlfanNJX1VHQUhQazEtZnBXTF9LYW5Ud3xBQ3Jtc0tuVjQ3V3B4aG5VTVhZWF90Tl9COElTLUxycGNRRUVxRFFveG5RVG1KYU96ekRpOWUzZF9XWE9iaDc3WVI0RE11cGRxNXA3VE9kUEc2VHlsNEJmLXdMQjNuWTk0SXZndmUyQ0hMbU84U1ROc24tZ2d3SQ&q=https%3A%2F%2Fgithub.com%2Fpokt-network%2Foperator&v=Tf9Qtr1gi3U)
* Demo code: [https://github.com/lander2k2/pocket-v...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbTFxcWdIQ2FBbENoamQ3THZhMkk2Y3F5QXl3UXxBQ3Jtc0ttWENzQlpEWktTSG8zYktqMEJLb3FkNEpLbVBfQzFzLWFhTjVTYVN2LXQyLWRpOXN6RUFMVWtUcjhIUW9VNkpEMC1Qc0VDbmZhX2pqanlDamdFLTQ3VWxOOHR1X0c0bFY4UWZ0NHlyQ3ROc2J1Ui03Zw&q=https%3A%2F%2Fgithub.com%2Flander2k2%2Fpocket-v1-operator&v=Tf9Qtr1gi3U)
* Operator Builder: [https://github.com/nukleros/operator-...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbEFtNDgwLTVCaDlGTjNKbEVmZENCZzYyZmFwUXxBQ3Jtc0tsbnoycUg3bmluLXdaQ0dScS1ZUU0tM00tMGVzOU9QRERGMUdrR3JoMmQwSVZQb0diSklwajBfaUJaNGlkaTRHSzM2bFZZcEE0clZKVnlyS003U0dYdE1RcUtlQ0lnRmZuM0dYZmd0WDNOT3MzN1BEQQ&q=https%3A%2F%2Fgithub.com%2Fnukleros%2Foperator-builder&v=Tf9Qtr1gi3U)
* Kubebuilder: [https://github.com/kubernetes-sigs/ku...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkkxTG1KVUI5eFczVGF5SnQ3eGdhZGxyWXFZZ3xBQ3Jtc0tsOU1Ic0VscGktU2NiMjV1bXBHcFFBbDgtb1dLZmxxQXVRaWsxQ3BCNjh0dkJGTHNZU09KbXRzRWR4NVdoWEhzMFVVR29ZaG5iN3NsRmJlRTg2UHI0MWtPLXV0RFBxUE5IM1pnVU90LTlqSWp2OFE3UQ&q=https%3A%2F%2Fgithub.com%2Fkubernetes-sigs%2Fkubebuilder&v=Tf9Qtr1gi3U)

**Comment by okdas** [comment]
> @okdas Could you link to the repo or any other resources/details that's tracking work for this?

We'll set up the tasks in a new repo (https://github.com/pokt-network/operator) and connect them to GH V1 Dashboard. 

That ticket was initially created to properly attribute the work, hence the starter pack label (as it was needed to import the task onto dework). We can probably nuke it since we have a separate repo now?

**Comment by Olshansk** [comment]
> We'll set up the tasks in a new repo ([pokt-network/operator](https://github.com/pokt-network/operator))

Nice.

> and connect them to GH V1 Dashboard.

Could you also connect this repo to that dashboard as well?
https://github.com/pokt-network/pocket-network-protocol

cc @jessicadaugherty for context that this may be possible

> That ticket was initially created to properly attribute the work, hence the starter pack label (as it was needed to import the task onto dework).

Got it.

> We can probably nuke it since we have a separate repo now?

If we do, we have to make sure contributor work is still synched to https://app.dework.xyz/pokt-network

cc @b3nnn  who can help with this

**Comment by Olshansk** [comment]
@okdas I've updated Dework (with @jessicadaugherty's help) to import issues from the operator repo as well:

https://app.dework.xyz/pokt-network/engineering-35121/settings/github

![Screen Shot 2022-09-07 at 12 17 26 PM](https://user-images.githubusercontent.com/1892194/188928961-312a79e2-960a-4b24-abef-bb76b89708a8.png)

**Comment by jessicadaugherty** [comment]
> Could you also connect this repo to that dashboard as well?
> https://github.com/pokt-network/pocket-network-protocol

if i can get admin permissions on these repos i can handle this @Olshansk

**Comment by Olshansk** [comment]
^ Invite sent

**Comment by Olshansk** [comment]
@okdas Can you link to the output of this ticket (youtube video, github repo, etc...) and we can close it out.

**Comment by jessicadaugherty** [comment]
https://www.youtube.com/watch?v=Tf9Qtr1gi3U&t=6s

[https://github.com/pokt-network/operator](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbmlTdUVFUEhFZW1JQmNWUTNnX0tFNXpXWTJPd3xBQ3Jtc0ttY1JXUzZfR2stc25oOWMyTkp4S05RYjdtRjNpQ3dqTVhwVFZ1VEtxSndEYlZYd3hLYWxqZklzalMtYkJlU1dicnNrLXBQZkdubDdWaUZuNGxCVGtXUVpaNVJVTGtvT2Q0ckNGbmIxbGNSNlVEbHU2SQ&q=https%3A%2F%2Fgithub.com%2Fpokt-network%2Foperator&v=Tf9Qtr1gi3U)
