### ISSUE TITLE
[Persistence] Fix gov parameters schema and enable usability

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#148]
# Objective
Simplfy gov parameters
Adopt the same schema architecture as the actors (sort=desc limit=1 etc.)

# Origin Document
The persistence module's parameter schema doesn't work with same block updates. 

It is also quite difficult to use to update easily and manage.

# Goals / Deliverables
- [ ] Deliver a code complete revamp of gov/params
- [ ] Deliver a document outlining the new architecture of the params and an updated list of them

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

---

Creator: @andrewnguyen22

**Comment by Olshansk** [comment]
@deblasis is already working on this in https://github.com/pokt-network/pocket/pull/139

<img width="1272" alt="Screen Shot 2022-08-05 at 11 20 25 PM" src="https://user-images.githubusercontent.com/1892194/183231541-4ac42481-c756-497a-ae5b-175c1569296d.png">

I'm going to take a first stab at reviewing that PR this weekend but just added you as a reviewer to take another look after

**Comment by andrewnguyen22** [comment]
closed with #139
