### ISSUE TITLE
[Persistence] Fix Persistence Module TODOs - Consolidate Postgres

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#149]
# Objective
A general cleanup issue is needed to tackle TODO's and ensure the persistence module is usable/readable by consolidating `PostgresContext` and `PostgresDb` as part of https://github.com/pokt-network/pocket/issues/172. 

# Origin Document
Should follow issue-#128, issue-#105, issue-#147 and issue-#148 the persistence module is messier and more difficult to understand than the developers would want for organic external contribution.

# Goals / Deliverables
- [ ] Run `log.
- [ ] Finish outstanding TODO's to ensure end-to-end functionality
- [ ] Consolidate `PostgresContext` and `PostgresDb` like so:
```go
type PostgresContext struct {
	height int64
	tx         pgx.Tx
	blockstore kvstore.KVStore	
}
```
- [ ] Avoid exposing `PostgresContext` and/or `PostgresDb` for testing purposes

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way
---

Creator: @andrewnguyen22
Co-creator: @Olshansk

**Comment by Olshansk** [comment]
Outside of the context of this, just figured I'd share that after we do a team massive cleanup of all our TODO tags, we can also automate it via https://github.com/pokt-network/pocket/issues/144.

@andrewnguyen22 Please also attach issues to the **V1 Dashboard** Projects so we can see it all in one place

**Comment by andrewnguyen22** [comment]
Good call ^

**Comment by Olshansk** [comment]
@andrewnguyen22 Per the discussion last friday, I'll take on persistence in the cleanup phase. I'll submit every bullet point here (and others) as a separate PR.

<img width="462" alt="Screen Shot 2022-09-11 at 4 00 23 PM" src="https://user-images.githubusercontent.com/1892194/189546711-23a1d486-26ad-49b7-89b1-55a2d3016951.png">
