### ISSUE TITLE
[Persistence] Base transaction indexer

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#151]
# Objective
- **CREATE** an `indexer` for arbitrary transaction bytes
- **USE** `protobuf3` (already used throughout the project) for encoding and a `filesystem db` for storage
- **INDEX** each transaction for `<sha3>hash`, `height`, `sender`, `recipient (if applicable)`
- **EXPOSE** an `interface` for write and read
- **TEST** create `unit`, `fuzz`, and `integration` tests

**Example interface**
 ```
type TxIndexer interface {  // TxIndexer interface defines methods to index and query transactions.

	// Index analyzes, indexes and stores a single transaction.
	Index(result *types.TxResult) error

	// GetByHash returns the transaction specified by hash or nil if the transaction is not indexed
	GetByHash(hash []byte) (*types.TxResult, error)

	// GetByHeight returns the transactions specified by height or nil if there are no transactions at that height
	GetByHeight(height int64) ([]*types.TxResult, error)

	// GetBySender returns the transactions signed by *sender* may be ordered descending/ascending
	GetBySender(sender address, descending bool) ([]*types.TxResult, error)

	// GetByRecipient returns the transactions *sent to address* may be ordered descending/ascending
	GetByRecipient(rec address, descending bool) ([]*types.TxResult, error)

	// DeleteFromHeight method added for pruning/rollback
	DeleteFromHeight(height int64) error
}

...
types/

type TxResult interface {
  Tx() Transaction        // the transaction object
  Height() int64          // height it was sent
  Index() int8            // which index it was within the block-transactions
  GetResultCode() int64   // 0 is no error, otherwise corresponds to error object code
  GetError() Error        // can be nil
  Signer() address        // get the address who signed
  Recipient() address     // can be nil
  MessageType() string    // corresponds to type of message (Ex. validator-stake, app-unjail, node-stake) etc.
}

type Transaction interface {
   // To be defined / for now it's just []byte
}

 ```

# Origin Document

Thus transaction storage (indexing) is a fundamental component of any blockchain system. For M1, this is *P0*

# Goals / Deliverables
- [ ] Code complete implementation 
- [ ] README and CHANGELOG for the indexer

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

---

Creator: @andrewnguyen22

**Comment by andrewnguyen22** [comment]
**Recommend** to use a filesystem db for the implementation

Currently we are between `Badger.db` and `Level.db`

Please use one of these two options

**Comment by phthan0** [comment]
90% sure I'm going to choose leveldb without even fully reading all the
information
