### ISSUE TITLE
[Core] Minimize shared module

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#163]
# Objective
- [ ] Assign all `structures` to respective modules
- [ ] Create shared `interfaces` that allow cross module sharing of objects without compromising ownership
- [ ] Avoid 1.18 generics and reflection when possible

# Origin Document
Most if not all structure ownership needs to be delegated to the respective packages in order to maintain the modularity of the design. The shared module is overgrown and requires a massive cutdown of ownership.

# Goals / Deliverables
- [ ] Code complete implementation
- [ ] Update all necessary documentation 

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

---

Creator: @andrewnguyen22

**Comment by andrewnguyen22** [comment]
If it's not clear by the issue description;

This issue is about properly scoping and encapsulating structures while maintaining shared interfaces within the shared package. 

This is a follow up to #154

**Comment by Olshansk** [comment]
@andrewnguyen22 

> Avoid 1.18 generics and reflection when possible

Agreed on trying to avoid reflections in prod.  However, I believe that using generics is a + as it improves code readability and reduces the code footprint. Happy to discuss offline

> Assign all structures to respective modules
> Create shared interfaces that allow cross module sharing of objects without compromising ownership

If you can break these two down in 2 (or more) PRs, I think it'll really help with conflict resolution and reducing the scope of the PR.

**Comment by andrewnguyen22** [comment]
You can't have one without the other

**Comment by andrewnguyen22** [comment]
> Agreed on trying to avoid reflections in prod. However, I believe that using generics is a + as it improves code readability and reduces the code footprint. Happy to discuss offline

Okay, not strong on this so I won't tackle. Although I'm willing to bet that once you see the interface versions of things, there might be an opportunity to achieve the same goal without reflection
