### ISSUE TITLE
[Telemetry] First iteration of Grafana Logging Dashboards for LocalNet

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#173]
# Objective
Prepare the infrastructure to enable centralized logging for a node in LocalNet.

# Goals / Deliverables
- [ ] A grafana dashboard that allows toggling logs by level (i.e. warn, error, debug, etc...)
- [ ] A grafana dashboard that allows toggling logs by module source (i.e. consensus, p2p, etc...)
- [ ] A list of requirements to the protocol team on how we need to format logging to enable this. E.g. this could entail a logging framework recommendation that we need to adopt
- [ ] A gif and README on how to enable this

# Non-goals
- Update the core implementation to enable the dashboards (if changes need to be made)
- Productionizing DevNet (not local) dashboards and telemetry

# Testing Methodology
- Manual flow using LocalNet
---

Creator: @Olshansk 
Co-Owners: @okdas @vlad-she

**Comment by okdas** [comment]
Taking care of this in https://github.com/pokt-network/pocket/issues/189
