### ISSUE TITLE
[Automation] Add make targets to group imports

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#185]
## Objective

Group imports across the entire codebase, while also deliniating between internal and external imports.

## Origin Document

This is a nicety 'code hygeine' target that was closed as low priority but re-raised by the engineering team.

See [this comment](https://github.com/golang/go/issues/20818#issuecomment-957171375) from the CirclCI team:

<img width="859" alt="Screenshot 2023-03-09 at 6 05 52 PM" src="https://user-images.githubusercontent.com/1892194/224204755-8d646c21-8b75-4972-8c3e-b6ad72166f6c.png">

See [this comment](https://github.com/pokt-network/pocket/pull/546/files#r1120746209) from the Pocket team:

<img width="799" alt="Screenshot 2023-03-09 at 6 06 09 PM" src="https://user-images.githubusercontent.com/1892194/224204821-083d715b-4fce-4e18-8868-72e90b65237e.png">

## Goals

- Organize & sort go imports through the whole codebase
- Group internal and external imports separately

## Deliverables

- [ ] A make target that triggers gosimports across the whole codebase
- [ ] A CI integration that triggers gosimports on any PR

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams
## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @andrewnguyen22 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@andrewnguyen22 Feel free to delete the two two lines next time you create a new issue

<img width="855" alt="Screen Shot 2022-09-03 at 1 17 17 PM" src="https://user-images.githubusercontent.com/1892194/188281536-2b07997d-64da-467f-a1e6-26e654ef5fc0.png">

**Comment by Olshansk** [comment]
@okdas Do you know if this is something the automation work you did can support by default?

**Comment by jessicadaugherty** [comment]
Removing from community bounty board until we can connect with @okdas about this @Olshansk

**Comment by Olshansk** [comment]
Low priority and not very imprtant. The automated linter handles the important parts

**Comment by Olshansk** [comment]
Reopening this issue per a discussion that happened here: https://github.com/pokt-network/pocket/pull/546/files#r1120746209

<img width="841" alt="Screenshot 2023-03-09 at 6 02 16 PM" src="https://user-images.githubusercontent.com/1892194/224204272-fb4e4ef3-ff9b-41a8-97c1-937eb4d698f8.png">
