### ISSUE TITLE
[LocalNet] CLI to deploy/scale actors on local environment

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#186]
## Objective

Allow to scale different actors on local (currently docker-compose) environment.

NOTE: This ticket is not super well-defined and needs context around how LocalNet is run (https://github.com/pokt-network/pocket/blob/main/docs/development/README.md). Reach out to @okdas for more details.

## Goals

- Allow to specify/change deployment replicas
- Support for different actors (validator, full-node, fishermen, etc)

## Deliverable

- [ ] Something similar to `make --config_paths=[] --gensis_path=[]`
- [ ] Make target that dynamically generates a docker-compose file with N replicas 
- [ ] Documentation on how we can add flags for other protocol actors in the future
- [ ] Create github issues to add other protocol actors to this in the future

## Non-goals / Non-deliverables

- Config generation (addressed separately https://github.com/pokt-network/pocket/issues/182)
- Support for fisherman or service nodes

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**:  @okdas 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@okdas When you have any research updates, please post them here.

**Comment by okdas** [comment]
This was done when the new LocalNet was released, here's related documentation page: https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md#scaling-actors
