### ISSUE TITLE
[DevNet] Automatically deploy DevNet from HEAD of main branch

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#188]
## Objective

We need to deploy DevNet whenever we update code in main branch.

## Goals

Whenever we have a new commit in the `pocket/pocket` repo main branch, deploy a new version.

TBD: new devnet from scratch, upgrade an existing devnet, or both?

## Deliverable

- [ ] Update DevNet yaml files/version on changes in main branch of https://github.com/pokt-network/protocol-infra repo

## Non-goals / Non-deliverables

- DevNet auto deploy from non-main branches (this is still manual when developer chooses to upgrade the remote deployment)

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @okdas 
**Co-Owners**: TBD

**Comment by Olshansk** [comment]
@okdas Please update deliverables and goals of this ticket

**Comment by Olshansk** [comment]
@okdas Is this done?

**Comment by okdas** [comment]
@Olshansk yes!
