### ISSUE TITLE
[docs] Broken links in docs

### ISSUE THREAD

**Issue by omahs** [pokt-network/pocket#191]
Hi, I noticed some broken links in your docs, those are the links:

https://docs.pokt.network/js/
https://docs.pokt.network/integrate/account-generation-validation/
https://docs.pokt.network/integrate/transaction-construction/
https://docs.pokt.network/integrate/transaction-verification/

**Comment by Olshansk** [comment]
Hey, appreciate you noticing these and submitting the PR! https://github.com/pokt-foundation/docs/pull/69

This repo is focused on the V1 implementation of the Pocket Network Protocol, so could you open a corresponding issue in the library where you added the PR? Specifically https://github.com/pokt-foundation

Side note: you lucked out on the PR # ;)

**Comment by omahs** [comment]
Sweet 😄 I didn't realize the PR #
Ok, I just added the issue there
