### ISSUE TITLE
[Utility] CLI Usage instructions and specification

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#193]
## Objective

Write a User Usage and a specification documenting the CLI features, quirks and whatnot, extending what has been (or not) already written in the CLI README (`app/client/cli/doc/README.md`)

This issue builds on top of https://github.com/pokt-network/pocket/pull/169 (in case it hasn't been merged into `main` at the time of reading)

## Origin Document

The CLI is going to be a multipurpose tool used by several personas interacting with Pocket Network.
We need a clear, detailed but concise document that covers the basics and HOWTOs when using and also developing/extending the CLI.

## Goals

- [x] Provide enough context and information so that all the basics and the foresaw FAQs about the CLI are covered. 

## Deliverable

- [x] A good CLI should be user-friendly and its use should feel natural. This means that the inline help provided by the CLI (Cobra) is also part of the documentation (for the user usage part)
- [x] The specifications should also cover a top-down description of the architecture of the module
- [x] Updated `app/client/cli/doc/README.md`

## Non-goals / Non-deliverables

- Do not cover the RPC spec since it's considered an implementation detail that might change and it's however documented in the relevant module.

## General issue deliverables

- [x] Update the appropriate CHANGELOG
- [x] Update any relevant READMEs (local and/or global)
- [x] Update any relevant global documentation & references
- [x] If applicable, update the source code tree explanation
- [x] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis
**Co-Owners**: ??

**Comment by deblasis** [comment]
First stab here https://github.com/pokt-network/pocket/pull/177/commits/e5c3ae5e532fcc38678c671bc9c48405dd748532

**Comment by jessicadaugherty** [comment]
Refactor against https://github.com/pokt-network/pocket/pull/235

**Comment by deblasis** [comment]
@Olshansk I believe this can be closed as part of #112 (since I have added the docs generator), do you agree or do you feel like there's more work to do here?

**Comment by Olshansk** [comment]
> @Olshansk I believe this can be closed as part of #112 (since I have added the docs generator), do you agree or do you feel like there's more work to do here?

💯% agreed!
