### ISSUE TITLE
[Utility] CLI - Non custodial Staking command

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#194]
## Objective

As implemented in #177, the CLI supports only `Custodial` staking. We need to support `Non Custodial` as well.

## Origin Document

This comment:
[Two separate subcommands - Can you create a follow-up issue to add support for non-custodial CLI support to avoid increasing the scope of this PR.](https://github.com/pokt-network/pocket/pull/177#discussion_r965182073)

## Goals

- [ ] Include a `NonCustodial` subcommand under the `Stake` command
- [ ] Identify the required arguments by referencing the [V0 implementation](https://github.com/pokt-network/pocket-core/blob/de8ec8c46cdcf17606b1491e2fca9f8ea3f7d716/app/cmd/cli/stake.go#L92-L100)
- [ ] Make sure that the `MessageStake` has all the necessary fields to support `NonCustodial` staking and that you are assigning the right values to them

## Deliverable

- [ ] Updated CLI with non-custodial staking command
- [ ] (optional) recommendations for non-custodial enhancements documented on the PR of this issue

## Non-goals / Non-deliverables

- Adding in additional stake commands
- Changing the behavior of non-custodial staking
- Updating the RPC

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
Considering for bounty. LMK of any objections @Olshansk

**Comment by Olshansk** [comment]
> Considering for bounty. LMK of any objections @Olshansk

The only thing to keep in mind is that the current custodial/non-custodial design is very v0-centric (1 address, 1 output, very limited), and I don't think this is a major priority for TestNet. 

With all of @h5law's work, this should be relatively straightforward to add, but I would also classify it as low priority. 

Personally, I think we can move this out into M5, and potentially start collecting what custodial/non-custodial should look like first (who can sign what, rev-share, multiple output address, etc...).

**Comment by jessicadaugherty** [comment]
Thanks @Olshansk agreed re: not a priority for testnet. I am looking for a task to get a contributor onboarded and started. They are a node runner so thought this would be a good one for them. Can ask their thoughts about any simple enhancements if feasible too. Also if you have another ticket that is good for onboarding someone but is higher priority I'm happy to move forward with that instead.

**Comment by Olshansk** [comment]
@Anaski99 do you still plan on tackling this?

**Comment by Anaski99** [comment]
I don't think so, no available bandwidth right now :(

**Comment by Olshansk** [comment]
This will be revisited as part of the E2E utility flows.
