### ISSUE TITLE
[Telemetry] LocalNet Dashboard for Node Health & Resource usage (basic)

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#197]
## Objective

Design and create a LocalNet dashboard that provides real-time monitoring of the health and resource usage of nodes in the network, including RAM, disk space, CPU usage, sockets, and other relevant metrics.

## Origin Document

?? Document from Lowell??

## Goals

- Develop a user-friendly dashboard interface that displays key metrics for each node in the network
- Provide a dashboard resource to help identify patterns and trends in node health and resource usage to gain  actionable insights that help optimize network performance and better react to performance issues

## Deliverable

- [ ] Document a proposed dashboard design and tracked metrics
- [ ] Review and add required events as needed and ensure their availability
- [ ] Build a Grafana dashboard that uses the required metrics

## Non-goals / Non-deliverables

- Dashboard alerting or monitoring
- Detailed visualizations 
- User provisioning 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
Goal: insight into V1 node resource usage (optionally public facing); incident of v1 node usage using industry standard metrics 
User: 1. DevOps 2. Protocol 3. Community
Deliverable: Grafana or other 3P tool dashboards and supporting infrastructure to deploy and use for node usage
Milestone: M2

**Comment by jessicadaugherty** [comment]
@Olshansk this is ready for review. Need info re: origin document. Thanks!

**Comment by okdas** [comment]
This has been done (basically ported an existing dashboard from devnets).
![image](https://github.com/pokt-network/pocket/assets/4950477/da842dc7-c491-455f-af0a-e6587cb1e2c7)

**Comment by Olshansk** [comment]
@okdas Looking forward to playing aroudn with this tomorrow!
