### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket#2]
Versions should be [semver 2](https://semver.org/) compatible, which is aligned with [golang's module versioning guidelines](https://go.dev/doc/modules/version-numbers).

I think we should start work with version "0.99.0" to begin with, which is a number that points towards v1, is below 1.x (denoting "in development"), and is far enough from v0's version number to differentiate it.

**Comment by iajrz** [comment]
Ah, I noticed a slight misread in the implementation vs specification, so this shouldn't be closed after all.

Format will be edited to conform to the format -- applied to our case, version number will look something like this:
`Major.Minor.Patch-branch.commit.dirty+race`

**Comment by iajrz** [comment]
In fact, the branch and commit don't quite fit into this scheme; the proper format should be `Major.Minor.Patch[-dirty]+branch.commit.race`, otherwise the branch name and commit hash would be used to determine precedence, and they shouldn't.

**Comment by luyzdeleon** [comment]
What would be the actionable here @iajrz ? Creating a PR ammending the docs?

**Comment by iajrz** [comment]
Action items:
- addition to mage.go to make it use tag information when available.
- Amending docs to explain what we actually do with versioning with the magefile.

**Comment by Olshansk** [comment]
@iajrz I want to create a tag & release for main https://github.com/pokt-network/pocket as a milestone finish line.

Following the instructions in https://github.com/pokt-network/pocket/tree/main/docs/build, what should it be?

**Comment by iajrz** [comment]
Tag `v0.0.1-alpha.01` is a good starting point; I think the build doc needs updating.

**Comment by Olshansk** [comment]
Per https://en.wikipedia.org/wiki/Software_release_life_cycle, I'll go with pre-alpha for now, but otherwise sounds good.

**Comment by Olshansk** [comment]
PR with documentation update here: https://github.com/pokt-network/pocket/pull/91/files

**Comment by Olshansk** [comment]
Going to close this out given the previous version update.

**Comment by Olshansk** [comment]
@Gustavobelfort I saw that you picked this up in #390. Make sure to assign to yourself so we can track who/where/what
