### ISSUE TITLE
V1 Prototype Integration

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket#20]
# Objective
First prototype build of the V1 project.

# Origin Document
The first fully end to end integrated V1 version including the following modules:

- **Application**: Provide an entrypoint to the application and start the `pocket` process.
- **Application Specific Bus and Shared Module**: The main integration point of the application, where the `pocket` process gets configured and initialized.
- **Persistence**: Have an in-memory database with the necessary persistence operations that happen in the application.
- **Utility**: A first prototype of the mempool and the implementation of the `Send` transaction be played against the state machine persisted using the Persistence module.
- **Consensus**: Pacemaker, round-leader election and basic hotstuff sub-module.
- **P2P**: Initialize the P2P module with a known set of peers, being able to broadcast messages to those peers and also being able to send direct messages to a particular peer.

Creator: @luyzdeleon 
Co-Owners: @andrewnguyen22 @Olshansk @derrandz 
Deliverables: 
- Initial prototype documentation per module
- How to build guide
- How to use guide
- How to test guide

**Comment by Olshansk** [comment]
With https://github.com/pokt-network/pocket/pull/88#issuecomment-1149386126 merged, we can close this out!
