### ISSUE TITLE
[Mockgen] For all test artifacts that are manually created

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#202]
\__DELETE_ME_: Please make sure to update the _Assigness_, _Labels_, _Projects_, _Milestone_ before submitting the issue\_
\__DELETE_ME_: Please make sure to add labels for the purpose (e.g. `persistence`) and priority (e.g. `low`) of this PR\_

## Objective

Use mockgen to create mocks in test_artifacts

## Origin Document

Currently - test_artifacts under the `shared module` mocks the genesis and config structures by hand. 

**IF we can continue to create proper genesis and config files for the debug client** we should use mockgen here.

## Deliverable

- [ ] Full mockgen implementation
- [ ] Supporting documentation

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @andrewnguyen22 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Superseded by runtime configs.
