### ISSUE TITLE
[TECHDEBT] Consolidate & encapsulate `ValidatorMap` logic

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#203]
## Objective

Encapsulate the concept of a `ValidatorMap` only to the consensus module

## Origin Document

[This discussion](https://github.com/pokt-network/pocket/pull/178#discussion_r965167220) in https://github.com/pokt-network/pocket/pull/178:

<img width="899" alt="Screen Shot 2022-09-11 at 3 15 53 PM" src="https://user-images.githubusercontent.com/1892194/189545145-72ddde0a-6712-4f23-bcd6-1e27fd2c9f42.png">

## Goals

- Remove all occurrences/references to the `ValidatorMap` throughout the codebase
- Only maintain knowledge/understanding o the `ValidatorMap` in the consensus module

## Deliverable

- [ ] Do a grep for `ValidatorMap` throughout the whole codebase and it should only show up in the consensus module
- [ ] A single PR refactoring / cleaning up this goal

## Non-goals / Non-deliverables

- Adding new functionality

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references

## Testing Methodology

- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Olshansk

**Comment by Olshansk** [comment]
This is related to #271 in the greater scope/vision of having dynamic validator sets as they change with each height.

#271 is scoped to only P2P and doing structured gossip amongst the validator nodes (for now). In general, P2P does care who the nodes are but simply gossips amongst the actors it is given.

This ticket is scoped to consensus (techdebt cleanup) to make sure the concept of a "validator set" only exists in consensus.

_As this is done (in isolation), the goal is to think how to implement dynamic additions of validators & P2P actors._

**Comment by deblasis** [comment]
@jessicadaugherty heads up I am a bit behind schedule with #331 and #203 (ValidatorMap related work). I was supposed to be done yesterday but I think I'll need another day or two to have them both under review.
