### ISSUE TITLE
[Persistence] Fix Persistence Module TODOs - Refactor persistence/genesis.go

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#209]
# Objective
A general cleanup issue is needed to tackle TODO's and ensure the persistence module is usable/readable by refactoring persistence/genesis.go as part of https://github.com/pokt-network/pocket/issues/172. 

# Origin Document
Should follow issue-#128, issue-#105, issue-#147 and issue-#148 the persistence module is messier and more difficult to understand than the developers would want for organic external contribution.

# Goals / Deliverables
- [ ]  Use generics to simplify the code in `persistence/genesis.go` as discussed in [this thread](https://github.com/pokt-network/pocket/pull/140#discussion_r939745088):
![Screen Shot 2022-08-14 at 11 18 43 AM](https://user-images.githubusercontent.com/1892194/184543679-dbdca18e-8126-455e-9925-1c71f5f5a6ce.png)

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way
---

Creator: @andrewnguyen22
Co-creator: @Olshansk

**Comment by Olshansk** [comment]
Outdated
