### ISSUE TITLE
V1 Prototype: Application entrypoint and shared module

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket#21]
# Objective
Add to the project the initial application entrypoint and the shared module with the common interfaces to all modules of the app.

# Origin Document
Pocket is going to use an application-specific-bus which is going to coordinate the integration of the different modules of the application, this requires a set of common-use interfaces and structures and the aim of this issue to provide those.

**Creator**: @luyzdeleon 
**Co-Owners**: @Olshansk @andrewnguyen22 @derrandz 

Deliverables:
- [ ] Modular code and interfaces to implement the application-specific bus
- [ ] Infrastructure (e.g. Dockerfiles) to run a localnet
- [ ] Tooling (CLI, commands, Makefile) to start localnet
- [ ] A quick design document specifying the design

Non-goals:
- Any "real" blockchain functionality

**Comment by Olshansk** [comment]
Submitted the first of several CLs here: https://github.com/pokt-network/pocket/pull/29.

There's no functionality but the modules are there. Will add documentation and a small design doc tomorrow.

**Comment by Olshansk** [comment]
The remaining action item to close this issue out is on me to provide documentation.

**Comment by Olshansk** [comment]
With https://github.com/pokt-network/pocket/pull/88#issuecomment-1149386126 merged, we can close this out!
