### ISSUE TITLE
[TECHDEBT][Persistence] Fix Persistence Module TODOs - Consolidate Actor

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#210]
# Objective
A general cleanup issue is needed to tackle TODO's and ensure the persistence module is usable/readable by consolidating `Actor` with `BaseActor` as part of https://github.com/pokt-network/pocket/issues/172. 

# Origin Document
Should follow issue-#128, issue-#105, issue-#147 and issue-#148 the persistence module is messier and more difficult to understand than the developers would want for organic external contribution.

# Goals / Deliverables
- [ ] Consolidate `Actor` in `persistence/schema/base_actor.go` with `BaseActor` in `persistence/schema/base_actor.go`.

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way
---

Creator: @andrewnguyen22
Co-creator: @Olshansk

**Comment by Olshansk** [comment]
@andrewnguyen22 Could you take this one on if you have some spare cycles?

**Comment by andrewnguyen22** [comment]
@Olshansk @jessicadaugherty during sync meeting we de-prioritized this in backlog for this sprint. I will pick up tickets accordingly in backlog if necessary
