### ISSUE TITLE
[TECHDEBT] consolidate `utilTypes.UtilActorType` with `utilTypes.ActorType`

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#227]
## Objective

Consolidate these two structures into one `proto enum` structure

## Origin Document

Two structures serve the same purpose in the Utility Module - they should be consolidated to one semantic structure.

## Goals

- Lower code footprint
- Lighten cognitive load

## Deliverable

- Code complete implementation
- Update Changelog.md

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @andrewnguyen22

**Comment by Olshansk** [comment]
@andrewnguyen22 Is this done?
