### ISSUE TITLE
[TECHDEBT] Shared Module, cleanup `testing_artifacts`

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#230]
## Objective

Cleanup all TODO's related to `testing_artifacts` in  the`shared` module.

## Origin Document

**Techdebt** week is emphasizing `code health` by removing `hacky` `placeholder` code. A lot of the 'shared structures' within testing_artifacts is just that.

(See applicable TODO's)

## Goals

- Reduce code footprint
- Encapsulate testing logic

## Deliverable

- Code complete implementation 
- Updated changelog.md

## General issue deliverables

- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @andrewnguyen22

**Comment by andrewnguyen22** [comment]
Unassigning myself from this issue because:
- [ ] It's blocked by #235
- [ ] It's controversial due to https://github.com/pokt-network/pocket/discussions/234
- [ ] It should be owned by who ever executes ^

**Comment by Olshansk** [comment]
I (or potentially someone on @adshmh's team) can help take this on.

In the meantime, @andrewnguyen22, could you take another look at #235?

**Comment by jessicadaugherty** [comment]
Blocked by #235

**Comment by Olshansk** [comment]
A lot has changed in the codebase so this ticket is no longer applicable
