### ISSUE TITLE
V1 Utility Module First Iteration

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#24]
# Objective
Create the first iteration of the Utility Module and integrate it with the other modules within the codebase

# Origin Document
Minimally implement the first iteration of the account based, state machine protocol. 
The module should create the fundamental actors:
- Accounts
- Validators
- Fishermen
- Applications
- Service Nodes

And implement the basic transaction functionality:
- Send-Tx

And minimally satisfy the following interface:
```
CheckTransaction(tx []byte) error
GetTransactionsForProposal(proposer []byte, maxTransactionBytes int, lastBlockByzantineValidators [][]byte) (transactions [][]byte, err error)
ApplyBlock(Height int64, proposer []byte, transactions [][]byte, lastBlockByzantineValidators [][]byte) (appHash []byte, err error)
```

The module may optionally create 'shells/TODOs' for the following transactions per actor
- Stake
- Unstake
- Edit Stake
- Pause
- Unpause

Creator/Owner: @andrewnguyen22
Co-Owner: @Olshansk
Deliverables: 
- Utility Module First Iteration
- How to build guide
- How to use guide
- How to test guide

**Comment by Olshansk** [comment]
@andrewnguyen22 Could you list me as a co-owner on this module? I'd like to be more involved in the utility module development as well as simply increase the bus factor.

**Comment by andrewnguyen22** [comment]
Done
