### ISSUE TITLE
V1 P2P Module - First Iteration

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#25]
### Objective
Create the first iteration of the P2P Module and integrate it with the other modules within the codebase.

### Origin Document
Implement the first iteration of a tcp server and client behavior with read, write and write with ack behaviors, in addition to basic Raintree broadcast (_with no redundancy or daisy chain cleanup_).

The module should implement:

* Lifecycle and Telemetry methodes:
- isReady
- finished
- log
- setLogger

* Network Behavior Methods
- listen
- send
- broadcast
- request
- respond
- ping
- pong

* Network IO Methods:
- open
- inbound
- outbound
- close
- read
- write
- poll
- answer

### Deliverables:

- [ ] An end-to-end go test script
- [ ] A 27 nodes stack simulating a near-real-life environment for e2e
- [ ] Code documentation

--------
Creator/Owner: @derrandz
Co-Owners: @andrewnguyen22 @oten91

**Comment by luyzdeleon** [comment]
@derrandz This issue is missing assignee, milestone and labels. It's also missing deliverables and co-owners.

**Comment by derrandz** [comment]
@luyzdeleon Thanks for the heads up! filled.

**Comment by Olshansk** [comment]
Going to close this issue out since the first iteration of the module implementation was merged in.
