### ISSUE TITLE
[Testing] Mock 10% Persistence Module in Utility Tests

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#261]
## Objective

Mock the Persistence Module for all Utility Testing

## Origin Document

The Utility Module relies on the Persistence Module in order to execute all of it's testing:

See 
```golang
func newTestPersistenceModule(_ *testing.M, databaseUrl string) modules.PersistenceModule {
```

Under `utility/test`

## Goals

- Enabling utility tests for persistence business logic that doesn't exist
- Remove cross module imports in Utility
- Allow complete encapsulation of test suite in Utility
- Create a clear and understandable `Mock`

## Deliverable

- Code complete implementation
- Plenty of comments in the `Mock`
- Updated changelog

## Non-goals / Non-deliverables

- Little nits that have nothing to do with the issue

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @andrewnguyen22

**Comment by Olshansk** [comment]
Idea posted in #290 as a starting point for a discussion.

**Comment by Olshansk** [comment]
I scrapped the first iteration of the idea (using a passthrough) and submitted a second one (using mocks only). Looking for preliminary feedback to see if it meets the requirements of the ticket before I put more effort into it

**Comment by Olshansk** [comment]
See #290 as a reference for future iterations on this work

**Comment by Olshansk** [comment]
We have been using the persistence module directly for utility tests, so am closing this out until we refactor the test suite.
