### ISSUE TITLE
[DOCUMENT] Interfaces for the M3 Relay Protocol

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#265]
## Objective

Code / document interfaces for the Relay Protocol to enable consensus and understanding around this piece of the M3 milestone.

## Origin Document

[M3 Milestone](https://github.com/pokt-network/pocket/blob/main/docs/roadmap/README.md#relay-protocol)

This is the first step into beginning the Relay Protocol development.

## Goals

- Clear interface(s) that show the lifecycle of the relay protocol
- Clear documentation supporting the above

## Deliverable

- Coded interface(s)
- Documentation support

## Non-goals / Non-deliverables

- Implementation of the interface

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @andrewnguyen22

**Comment by jessicadaugherty** [comment]
Is there a PR for this?

**Comment by Olshansk** [comment]
Yup, right here: https://github.com/pokt-network/pocket/pull/306

**Comment by jessicadaugherty** [comment]
Thanks @Olshansk for linking and pointing out the timeline above!
