### ISSUE TITLE
[TECHDEBT] [P2P] Remove stdNetwork and simplify `Network` interface

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#266]
## Objective

Tend for the TODO items:

```
./p2p/types/network.go:// TECHDEBT(olshansky): When we delete `stdnetwork` and only go with `raintree`, this interface can be simplified greatly.
./p2p/stdnetwork/network.go:// TECHDEBT(olshansky): Delete this once we are fully comfortable with RainTree moving forward.
```

Refine the goals / priority of this issue since it looks like it has dependencies like "being comfortable with RainTree"

## Origin Document

[ Why? Issue justification and/or link to another document]

## Goals

- _\_*REPLACE_ME*: List of things that are high level ideas or goals driving the task_
- [ ] ...

## Deliverable

- _\_*REPLACE_ME*: List of things that are concrete deliverables_
- [ ] ...

## Non-goals / Non-deliverables

- _\_*REPLACE_ME*: List of things that are out of scope_
- ...

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Not a high priority, so I'm moving this to M QOL

**Comment by Olshansk** [comment]
@bryanchriswhite Can you review if we can close this out?
