### ISSUE TITLE
[TECHDEBT] [P2P] Remove Topic from messaging

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#267]
## Objective

Tending for the TODOs:

```go
./shared/modules/p2p_module.go:	Send(addr cryptoPocket.Address, msg *anypb.Any, topic debug.PocketTopic) error // TECHDEBT: get rid of topic
./shared/modules/p2p_module.go:	Broadcast(msg *anypb.Any, topic debug.PocketTopic) error                       // TECHDEBT: get rid of topic
```

## Origin Document

Tech debt

## Goals

- [ ] Remove topic from our messaging bus

## Deliverable

- [ ] Make sure that the current functionality is preserved without relying on topic

## Non-goals / Non-deliverables

- Any breaking changes in functionality apart from topic removal

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
For context, I think the topic should be inside of the message. No reason for an extra param in the interface
