### ISSUE TITLE
[TECHDEBT] [P2P] Conntype as enum

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#268]
## Objective

There are TODOS where ConnType are booleans that should be updated to be enums so we can have more descriptive values where desired as they relate to P2P network actors. 

```go
./p2p/transport.go:	switch cfg.IsEmptyConnType() { // TECHDEBT kept in switch format because this should be an enum not a bool
./p2p/types/p2p_config.pb.go:	IsEmptyConnectionType bool   protobuf:"varint,4,opt,name=is_empty_connection_type,json=isEmptyConnectionType,proto3" json:"is_empty_connection_type,omitempty" // TODO (Drewsky) switch back to enum
./p2p/types/proto/p2p_config.proto:  bool is_empty_connection_type = 4; // TODO (Drewsky) switch back to enum
! touches shared/types
```

## Origin Document

[TODO in the code](https://github.com/pokt-network/pocket/blob/main/p2p/transport/transport.go#L17)

## Goals

- Convert P2P booleans to enums

## Deliverable

- [ ] A PR that addresses the above TODOs

## Non-goals / Non-deliverables

- Defining additional enum values
- Updating logging logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis and @jessicadaugherty 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
- EmptyConnection is used for testing
- TCP is used for prod / development
- In the future, we may explore UDP or QUIC

An enum should be low effort to help facilitate this optionality.
