### ISSUE TITLE
[TECHDEBT] [P2P] Find a way to avoid self broadcast when calling NetworkBroadcast

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#269]
## Objective

Tend for the TODO: 

```go
./p2p/stdnetwork/network.go:// TODO(olshansky): How do we avoid self-broadcasts given that AddrBook may contain self in the current p2p implementation?
```

Clarify with @Olshansk the scope and detail below before start working on it.

### Note to self (pun not intended):
self is at index 0 in the sorted addrbook in the raintree implementation, see if we can naively implement something similar in stdnetwork, unless it's not worth it since stdnetwork seems to be on its way for sunsetting already (see #266)

## Origin Document

[ Why? Issue justification and/or link to another document]

## Goals

- _\_*REPLACE_ME*: List of things that are high level ideas or goals driving the task_
- [ ] ...

## Deliverable

- _\_*REPLACE_ME*: List of things that are concrete deliverables_
- [ ] ...

## Non-goals / Non-deliverables

- _\_*REPLACE_ME*: List of things that are out of scope_
- ...

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Let's just go with the SUPER naive and super inefficient approach to get this done.

stdnetwork is used to be a backup until we're fully comfortable with raintree.

**Comment by bryanchriswhite** [comment]
I'm closing this for now as stdnetwork is long gone. I don't think this is actionable anymore. We can always re-open or open new issue if we discover a loose end.
