### ISSUE TITLE
[TECHDEBT] [P2P] Raintree scalability improvements

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#273]
## Objective

Tend for the TODOs:
```go
// INVESTIGATE(olshansky/team): Does not scale to 1,000,000,000 nodes
```

Related to #222 and #246

## Origin Document

**"make it work ⏩ make it fast ⏩ make it pretty"**

#222 improves a lot in terms of time complexity, see what we can do to improve even further. 

Some research might be required

## Goals

- [ ] Ensure that the network can scale
- [ ] Verify empirically

## Deliverable

- [ ] Optimizations
- [ ] Tests / Benchmarks

## Non-goals / Non-deliverables

- _\_*REPLACE_ME*: List of things that are out of scope_
- ...

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Moving this to `M4`

**Comment by Olshansk** [comment]
Closing this out as the scope is too large.
