### ISSUE TITLE
[TECHDEBT] [P2P] Raintree test suite improvements: Double check expected calls counting

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#277]
## Objective

Tend for this TODO left in the code:

```go
./p2p/module_raintree_test.go:// INVESTIGATE(olshansky): Double check that how the expected calls are counted is accurate per the
```

## Origin Document

Looking at the configuration for a single RainTree test:

<img width="659" alt="Screen Shot 2022-10-15 at 4 49 52 PM" src="https://user-images.githubusercontent.com/1892194/196007035-168a6865-848a-4756-882b-526d23bfc87c.png">

Along with the visuals and the configs for a single test:

<img width="776" alt="Screen Shot 2022-10-15 at 4 38 07 PM" src="https://user-images.githubusercontent.com/1892194/196006821-2b37be84-7e1e-41ac-aa51-b3c796ca7b8e.png">

It is not clear what these are supposed to mean in the context of gossip.

## Goals

- [ ] Make the RainTree testing framework counters more intuitive in terms of reads/writes from/to the network
- [ ] Add some clarifying documentation to the RainTree testing framework/modules

## Deliverable

A PR that includes the following
- [ ] Changes to how the RainTree testing framework counters are managed and validated
- [ ] Supporting documentation on what the counters mean and why

## Non-goals / Non-deliverables

- Modify Raintree implementation
- Code cleanup
- Code refactoring
- Add the tooling/utilities to gain visibility into RainTree
- Add the tooling/utilities to generate RainTree unit tests

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- **Task specific tests**: `make test_p2p`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
This is being tackled in #179.
