### ISSUE TITLE
[TECHDEBT] Change the `PersistenceRWContext` interface to pass `paramName` when getting a parameter

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#286]
## Objective

Deprecate 
- [ ] `GetBlocksPerSession(height int64) (int, error)`
and
- [ ] `GetServiceNodesPerSessionAt(height int64) (int, error)` 

for 

- [ ] `GetParameter(paramName string, height int64) (interface, error)`

## Origin Document

We genericized the param setters like:

`SetParam(paramName string, value interface{}) error` 

We need a similar pattern for getters

## Goals

- Lower code footprint,
- Remove placeholder constants
- Maintain a strict pattern

## Deliverable

- Code complete implementation
- Updated documentation

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
---

**Creator**: @andrewnguyen22

**Comment by Olshansk** [comment]
Great `starter task`!

**Comment by Jasonyou1995** [comment]
I might need some help to get started (some super basic questions):

- Task questions
    - Do I need to implement the `GetParameter` function?
    - Should I comment out the two deprecated functions `GetBlocksPerSession` and `GetServiceNodesPerSessionAt` then combine them to `GetParameter`? 
    - I saw the `./utility/context.go` and `./persistence/module.go` scripts are using this interface, should I update them all?
- Goal questions
    - What does “lower code footprint” means?
    - Does the “maintain a strict pattern” means using `golangci-lint` or `make go_lint` for format checking?
- Documentation questions
    - What is the specific documentation I should update other than CHANGELOG? 

Thank you!

**Comment by Olshansk** [comment]
> Do I need to implement the GetParameter function?
Yes.

> Should I comment out the two deprecated functions GetBlocksPerSession and GetServiceNodesPerSessionAt then combine them to GetParameter?
Yes.

> I saw the ./utility/context.go and ./persistence/module.go scripts are using this interface, should I update them all?
Yes.

> What is the specific documentation I should update other than CHANGELOG?
For this change, since it's small. The changelog is enough.

**Comment by h5law** [comment]
I would be interested in taking up this task if its still relevant. The only question I have is around determining the type from the `paramName` argument to the `GetParameter` function.

If the function is solely to replace the two ones listed why not use this function which is already defined? As both the functions are int32 types if I am correct.
```
func (p PostgresContext) GetIntParam(paramName string, height int64) (int, error) {
	v, _, err := getParamOrFlag[int](p, types.ParamsTableName, paramName, height)
	return v, err
}
```

However, if you are aiming to really generalise the 3 wrappers for the `getParamOrFlag` function you would need to know the type of the parameter. Or simply just return it as a string. Please let me know if I am wrong here as I am not super familiar with the codebase.

I think this involves editing the following files:
```
shared/modules/persistence_module.go <-- comment out old functions define new function in interface
persistence/gov.go <-- comment out old functions add new GetParameter function logic
utility/gov.go <-- Comment out GetBlocksPerSession replace with GetParameter? (This seems like it may not be correct)
shared/modules/mocks/persistence_module_mock.go <-- Comment out mocks of old functions replace with GetParameter mocks
```
In addition to the `CHANGELOG.md`

Let me know the situation I am happy to get to work. The main question is about knowing the type the `paramName` string will return from the database.

**Comment by h5law** [comment]
@Olshansk what do you think about this?

**Comment by Olshansk** [comment]
> I would be interested in taking up this task if its still relevant

Yup, still relevant!

> If the function is solely to replace the two ones listed why not use this function which is already defined? As both the functions are int32 types if I am correct.

This is the first step of this task and what I would call the "first commit" as you start working on it locally. It is to simply make these two functions follow the same pattern as the rest of the codebase by using `SetParam(paramName string, value interface{}) error` from the `PersistenceModule interface`.

<img width="1496" alt="Screenshot 2022-12-28 at 2 27 35 PM" src="https://user-images.githubusercontent.com/1892194/209862797-cf0db75d-8cd9-431e-8043-707d71178642.png">

> However, if you are aiming to really generalise the 3 wrappers for the getParamOrFlag function you would need to know the type of the parameter. Or simply just return it as a string. Please let me know if I am wrong here as I am not super familiar with the codebase.

Similar to how we have `SetParam(paramName string, value interface{}) error` in `PersistenceModule`, we were thinking of adding a `GetParam(paramName string, height int64) (interface{}, error)` to `PersistenceReadContext`. There might even be an opportunity to use `GetParam[T int | string | []byte](paramName string, height int64) (T, error)` so the caller doesn't have to type cast it explicitly after retrieving the data.

In terms of files that'll be affected, you're on the right track.

_Disclaimer: I haven't tried implementing the suggestion above so there may be some hurdles I'm unaware of._

--- 

cc @deblasis for context. I know you're planning on making some other changes to the persistence interface and curious what you think about this change.

**Comment by h5law** [comment]
@Olshansk I have actually wrote the code for this PR and update the unit test in `utility/test/gov_test.go` (all working successfully) I ended up going for an automatic type detection method by checking the types in the genesis_state protobuf (but reading the json tag to avoid having the proto imports used) I will open a PR so you can check it out and I don't mind changing to your proposed method as it will probably be easier to have explicit types given. My method will also never allow for a `[]byte` return type as none of the functions in the genesis state actually have this type (reading this from `persistence/types/persistence_genesis.pb.go`). I'll get to work on the PR and the changes now

**Comment by deblasis** [comment]
@Olshansk 
> cc @deblasis for context. I know you're planning on making some other changes to the persistence interface and curious what you think about this change.

Hi @h5law !

>I would be interested in taking up this task if its still relevant. The only question I have is around determining the type from the paramName argument to the GetParameter function.

In order to determine the type of the params we can leverage the  struct tags 

![image](https://user-images.githubusercontent.com/29378614/209864487-489d3b7c-adbe-4fc7-b0d0-25f796ff5ba7.png)

These are parsed in `parseGovProto()` which should return everything you need to move forward. Do not hesitate if you have any questions.

Oh as I was writing I saw your message and it seems you already found your way :) well done!
