### ISSUE TITLE
[Telemetry] Apply shared logging module

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#288]
# Objective
Use the foundations to unify and standardize the logging approach across the entire codebase created in https://github.com/pokt-network/pocket/issues/164 and apply to a subset of files to use this framework.

# Origin Document

See the github discussion for full details: https://github.com/pokt-network/pocket/discussions/214

The implementation of this was started by @derrandz here: https://github.com/pokt-network/pocket/pull/162.

This ticket can either build on top of the existing WIP or use those learnings and apply them to a different approach.

# Goals / Deliverables
- [ ] Select subset of files to use the same logging framework
- [ ] Add support for multiple log levels
- [ ] Add support for attaching labels to logs
- [ ] ~~Build a log panel in Grafana where logs can be toggled based on level or label~~ (covered in #189)

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the appropriate README on how to use and test this feature
- [ ] Update any relevant global documentation & references
- [ ] Add a video and/or gif on how to use feature
- [ ] Document small issues / TODOs along the way

# Non-goals
- Add new logs throughout the codebase
- Improve the explicitness or correctness of existing logs
- Add new business logic functionality

# Testing Methodology
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
Remove

---

Creator: @Olshansk

**Comment by Olshansk** [comment]
@jessicadaugherty I've udpated the milestone + labels

**Comment by jessicadaugherty** [comment]
Note to self/team: revisit #301 after completing #288

**Comment by Olshansk** [comment]
![Screenshot 2022-12-22 at 3 56 59 PM](https://user-images.githubusercontent.com/1892194/209227856-50ed4f37-2019-435e-9ca9-7c94ce451d48.png)

@Gustavobelfort As you go into this work and integrate it with Grafana (or other), I wanted to share what my dream feature here would be:

- Being able to filter by level `WARN`, `DEBUG`, etc..
- Filtering / toglging by stuff like `node1.consensus`, `node2.consensus`, etc...
- Filtering / toggling by `REPLICA` / `LEADER`
- Aggregating across `event_*`

I'm sure we'll have all of these over time, but wanted to drop my thoughts in case you have better ideas :)

**Comment by jessicadaugherty** [comment]
Hey @Gustavobelfort! I left a note for myself above to revisit https://github.com/pokt-network/pocket/pull/301 after this was completed in the event of any TODOs or NITs coming out of applying the logger throughout the codebase. Can you lmk if you saw anything that fits that category along the way so we can document it for the future? Ty!
