### ISSUE TITLE
[Shared] Config and Genesis refactoring improvement: make sure we can `ValidateConfig` and `ValidateGenesis` with both real and mocked implementations

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#293]
## Objective

Keep track and address areas of improvement. Specifically, in this issue we aim at addressing the comments below (which are related)

Related PR #235

## Origin Document

- https://github.com/pokt-network/pocket/pull/235#discussion_r986214256
- // DISCUSS (team): we cannot cast if we want to use mocks and rely on interfaces ([source](https://github.com/pokt-network/pocket/pull/235/files/0fac63e35f1f080e2aa4b304858f35768ee1c1fb#diff-eba95a8b904f8186683d2f9c106a3dc021f014918420e6a074d0a2b4e59c261dR198))

## Goals

- [ ] Improved code quality

## Deliverable

- [ ] Implementation that improves/enables better testing and safety within modules

## Non-goals / Non-deliverables

- Changes in logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## [Optional] Testing Methodology

- \__REPLACE_ME_: Make sure to update the testing methodology appropriately\_
- **Task specific tests**: `make ...`
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@deblasis Is this an intentional duplicate of #294 or can we close one out?

**Comment by deblasis** [comment]
> @deblasis Is this an intentional duplicate of #294 or can we close one out?

Copy-pasta mistake. This one had the wrong title. I have renamed it.

**Comment by deblasis** [comment]
We are using interfaces now, this can be closed
