### ISSUE TITLE
[TECHDEBT][Shared] Address legacy Run golangci-lint errors

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#295]
## Objective

Improve unit tests by addressing legacy linting errors 

## Origin Document

Raised by review of https://github.com/pokt-network/pocket/pull/235#issuecomment-1270639788

![Screen_Shot_2022-10-06_at_10 50 28_AM](https://user-images.githubusercontent.com/55156619/194425205-473f6575-4eeb-49de-a761-f23e5bbcecf6.png)

## Goals

- Block PRs that break unit tests
- Block PRs that break linting errors
- Display code changes that do not follow style guidelines 

## Deliverables

- [ ] A PR that tends to all of the legacy linting errors in the repo
- [ ] A PR that updates the linting github workflow to block (rather than simply display a warning) on golang and repo linting errors

## Non-goals / Non-deliverables

- Changing any business logic in the codebase

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @jessicadaugherty
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@jessicadaugherty Can we include this in iteration 4? It's a lower priority, but it blocks us from enabling the autolinters

**Comment by h5law** [comment]
@jessicadaugherty I'll do this (I don't know when iteration 4 is but can have it done this week). I find these errors annoying anyway so it'll be nice to get rid of em!

**Comment by jessicadaugherty** [comment]
Amazing, thanks @h5law! I assigned this out to you on DeWork. LOL iteration 4 was in like October or something so this was originally a priority backlog item that kept getting refactored. Agreed it would improve contributor QoL! Appreciate it.

> Just to confirm - fix the errors from the golanglint-ci test throughout the codebase and make the workflow blocking on failure?

Exactly! I'd take a look at the linked PR in "Origin Document" for more context on where we stumbled on this need. And, of course, lmk if you have any questions!

**Comment by okdas** [comment]
Hey @h5law, thank you for looking into this!

Here is a related thread: https://github.com/golangci/golangci-lint-action/issues/23

Basically, from what I understand, the packages are getting downloaded by `golangci-lint-action` are already present because of golang cache. Or due to the fact we need to generate mocks and all that stuff that requires us to download the packages prior to executing `golangci-lint-action`. Lmk if you have any questions — I've looked into that briefly a couple of months ago but never committed a change.

**Comment by Olshansk** [comment]
Just wanted to provide some context to what @okdas mentioned.

@h5law is working on enabling the golang CI linter by tending to **ALL OF** the issues it raises throughout the codebase.

One of the many such issues is the fact that there is a ❌ when the `test_results.json` is being uploaded. The following screenshot is taken from [this link](https://github.com/pokt-network/pocket/actions/runs/4046603282)

![Screenshot 2023-01-31 at 9 06 38 AM](https://user-images.githubusercontent.com/1892194/215850058-1931b3c3-9169-4be7-a0b3-0164aad0a63e.png)

The important to note is that this is a **false positive**. The file gets uploaded and there is no real issue. However, seeing a red X can cause confusion and lead to developers spending time looking in a place where there is no problem.

The information Dima provided is a potential starting point to understand how/if we could resolve this as well.
