### ISSUE TITLE
[Infrastructure][LocalNet] Investigate & determine if kubernetes / minikube should be used in place of docker-compose

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#299]
## Objective

As we continue to build V1 localnet, we should evaluate our tooling to ensure our deployment and management pipelines are scalable and easily configurable. Currently we use docker-compose, but this should be evaluated against options like Kubernetes/Minikube to identify what works best for our stack.

## Origin Document

@olshansky?

## Goals

- [ ] Recommend a path forward for how we scale and configure localnet

## Deliverables

- [ ] Provide a 1-2 pager summarizing the tradeoffs between Minikube vs Kubernetes vs Docker Compose with a focus on: 
   - [ ] Ease of use 
   - [ ] Ease of comfortability
   - [ ] Time to completion/to code changes
   - [ ] Compatibility with Docker File

## Non-goals / Non-deliverables

- Implementing any new desired infrastructure tooling

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way
---

**Creator**: @jessicadaugherty
**Co-Owners**:

**Comment by Olshansk** [comment]
Per my comment in https://github.com/pokt-network/pocket/issues/298#issuecomment-1281763062, @okdas would this be mutually exclusive from k8s operators or is there a world where we use both minikube AND k8s operators?

I'm not familiar with the overlap of those two technologies, which is why I ask.
