### ISSUE TITLE
[P2P] RainTree Unit Test Generation Tooling

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#314]
## Objective

Provide a tool (e.g. make target) that triggers underlying scripts (e.g. python code or a jupyter notebook) to generate ascii art and unit tests for RainTree.

## Origin Document

In order to make the RainTree clearer to understand (e.g. #304), easier to maintain (e.g. this ticket) and extend it to other features (e.g. #276), we need to make sure the tools used to generate the ASCII art and values for the unit tests live alongside the tests themselves:

<img width="820" alt="Screen Shot 2022-10-19 at 7 27 27 PM" src="https://user-images.githubusercontent.com/1892194/196841874-959f6a4d-afcb-465c-b325-6109730115f9.png">

## Goals

- [ ] Make it easier to add new RainTree unit tests (and enable fuzzing in the future)
- [ ] Make it easier to maintain RainTree unit tests (by anyone, new or old on the team)
- [ ] Remove any black boxes used in RainTree test framework generation

## Deliverable

- [ ] A python script that generates ASCII art + golang formatted RainTree unit tests
- [ ] A make target used to trigger the python script above
- [ ] Documentation explaining how the above script + target works
- [ ] Documentation explaining how use above script + target

## Non-goals / Non-deliverables

- Change or modify RainTree implementation
- Adding new functionality to the RainTree testing framework
- Adding a suite of new unit tests (only 1 for validation)
- Adding fuzzing tests

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- Use the tools here to add one single unit test for verification
- **All tests**: `make test_p2p`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Olshansk 
**Co-Owners**: @Olshansk

**Comment by andrewnguyen22** [comment]
I'd even go further to ask the ticket include dynamic **fuzz** test generation using a `golang` version of the generator. WYT? @Olshansk

**Comment by Olshansk** [comment]
> I'd even go further to ask the ticket include dynamic **fuzz** test generation using a `golang` version of the generator. WYT? @Olshansk

I'd prefer to create a follow-up ticket for that to prevent the scope of this issue from getting too large.

I'm closing to getting https://github.com/pokt-network/pocket/pull/316/files up for review soon (not ready yet), and it is already quite big. The immediate goal right now (and of this ticket) is to simply remove the "black box" of how the unit tests are generated, and we can later increase the test coverage and complexity with fuzzing and such.

Once that's up, I'd like to focus on the state hash, which is a higher priority, and the tooling that's a result of this can even be used by someone else to create the fuzz testing in a separate issue.
