### ISSUE TITLE
[CLI] Issues with client command: connection refused after running `ResetToGenesis`

### ISSUE THREAD

**Issue by Jasonyou1995** [pokt-network/pocket#322]
## Objective

CLI encounters connection issue after running `ResetToGenesis`

## Origin Document

Error writing to the peer during send:  dial tcp4 172.18.0.7:8080: connect: connection refused

https://user-images.githubusercontent.com/15693947/199839525-0a0424ba-ff93-4538-87d9-626770435d39.mov

## Goals

* Finding out the cause of the issue
* Then try to address it

## Deliverable

- [ ] Finding the root issue
- [ ] Comment on the issue
- [ ] Change or update the source code if necessary
- [ ] Update CHANGELOG

## Non-goals / Non-deliverables

- Changing existing functionality.

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: Jasonyou1995
**Co-Owners**: [optional - github usernames of the co-owner(s)]

**Comment by Olshansk** [comment]
A few nites on updating this issue description

![Screen Shot 2022-10-27 at 11 28 41 AM](https://user-images.githubusercontent.com/1892194/198370463-a8473878-4346-493a-a2f6-45beba101b6b.png)
