### ISSUE TITLE
[SPIKE][Consensus] Remove `validatorMap` from the `consensusModule` struct

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#331]
## Objective

Remove `validatorMap` from the `consensusModule` struct state & access it from the persistence layer (added n the past) 

The `validatorMap` is just a placeholder for the global `ValidatorSet` which is stored at the persistence layer. 

*NOTE: this is a multi-module issue*

## Origin Document

Originally scoped in issue #315 - separate issue to downscope

## Goals
- [ ] Remove `validatorMap` from the `consensusModule` struct and port it to the persistence module's `GetActor(s)` (Validator) 
- [ ] Update Changelog.md

## Deliverable
- [ ] Code complete
- [ ] Supporting documentation

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @andrewnguyen22

**Comment by deblasis** [comment]
@jessicadaugherty heads up I am a bit behind schedule with #331 and #203 (ValidatorMap related work). I was supposed to be done yesterday but I think I'll need another day or two to have them both under review.
