### ISSUE TITLE
[Shared][CodeHealth] Allow to create only Initializable modules

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#333]
## Objective

Currently, all modules implement `Module` interface, which includes `IntegratableModule` and `InterruptableModule` interfaces which are not needed for all modules, only for some. We should look if we can adjust Create() to return `InitializableModule` instead of `Module`.

```
type InitializableModule interface {
	GetModuleName() string
	Create(runtime RuntimeMgr) (Module, error)
}
```

## Origin Document

We first found this while [implementing logger module](https://github.com/pokt-network/pocket/pull/301#discussion_r1012045703), which does not need a bus.

## Goals

- An ability to create modules that only implement `InitializableModule` interface.

## Deliverable

- [ ] Modules do not need to implement noop functions when they are not necessary (e.g. `LoggerModule` may not depend on `IntegratableModule` interface).

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @okdas 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@okdas Thanks for creating the ticket. Suggesting a few nits below:

<img width="1179" alt="Screen Shot 2022-11-02 at 7 30 49 PM" src="https://user-images.githubusercontent.com/1892194/199637377-0ec2eb24-83e1-415e-8f41-d73b2baf9f95.png">

**Comment by Olshansk** [comment]
Closing this out as @bryanchriswhite has done a lot of work on this since the issue was first created.
