### ISSUE TITLE
[P2P] Integrate LibP2P

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#347]
# Objective
Use the results of https://github.com/pokt-network/pocket-network-protocol/issues/17 to integrate LibP2P into the p2p module.

# Origin Document(s)
* https://github.com/pokt-network/pocket-network-protocol/issues/17
* [LibP2P Guide](https://docs.libp2p.io/guides/)

# Goals

- Integrate LibP2P into Pocket Core

# Deliverables
- [x] MVP integration where LibP2P transport layer is used to send messages

# Non-Goals / Deliverables
- Integrating P2P deeper into transport layer
- Implementing peer churn or discovery
- Exhaustively enabling all the features we will need from LibP2P

## General issue checklist
- [ ] Update the appropriate CHANGELOG
- [ ] Update the README
- [ ] Update the source code tree explanation
- [ ] Update any relevant global documentation & references
- [ ] Document small issues / TODOs along the way

---

Creators: @jessicadaugherty @Olshansk

**Comment by Olshansk** [comment]
Per our team discussion, I believe the scope of this can be summarized to, at a very high level, to bullet point 3 from [the research SPIKE](https://github.com/pokt-network/pocket-network-protocol/issues/17#issuecomment-1315936241):

<img width="957" alt="Screen Shot 2022-11-15 at 2 19 31 PM" src="https://user-images.githubusercontent.com/1892194/202037095-281429e8-9a46-4d98-b9f9-72d667cd334b.png">

**Comment by jessicadaugherty** [comment]
Embed LibP2P host in Pocket host. Do not enable.

**Comment by Olshansk** [comment]
Synched up @bryanchriswhite on this offline and wanted to capture the potential action items for a next step.

**Idea**: LibP2P could be treated as another "connection type" similar to what we implemented in #268.

**Next steps**:
1. Add `LibP2P` as a connection type (alongside TCP & noop)
2. Create a new ticket titled "Consolidate LibP2P & Pocket Interface"
3. "Hack" things together (in terms of data types) to replace the transport layer in P2P
4. Add comments similar to `CLEANUP(#XXX): Cleanup these interfaces` wherever we kind of hacked things together

**Other things discussed**:
1. Lack of connection pooling in the current version was not an intentional "thought-through" deicsion - we just got things working using the standard Golang libraries and I did not document it explicitly.

**Comment by Olshansk** [comment]
> What is the difference between hacking things together in terms of data types and being deliberate and targeting them one by one (wherever possible) in a more controlled manner?

@bryanchriswhite did research on all the [data types](https://www.notion.so/pocketnetwork/LibP2P-integration-d4141df68ae94afdba766679b3707914) but it's still a big undertaking.

I thought that if we just wire it together (with TODOs and a separate connection type) everywhere, we'd be closer to this approach and clean it up after:

![Making-sense-of-MVP-](https://user-images.githubusercontent.com/1892194/217359781-af43bea2-8a23-4144-9ca9-3f9521207044.jpg)

> Re: connection pooling, I think it's necessary for the long...

We're on the same page. It seems like it's the default and Bryan mentioned we have to make an explicit effort to turn it off. If it's less effort to keep it (during initial integration), let's keep it.

---

@bryanchriswhite This is an integration where I haven't jumped in to get my hands dirty so I'm speaking out of my depth. However, if you think it'd be helpful for me to get a foundation PR up, lmk.

**Comment by bryanchriswhite** [comment]
@Olshansk sorry for the delay in responding, I've been heads-down in preparation for being able to participate meaningfully. 😅

In my view, it's looking like the path of least resistance is to implement a new `modules.Module` and `types.Network`. I also figured that it would then be more straightforward to add a boolean config flag rather that coupling to the connection type.

I still fill in the PR description with more details when I'm back at my desk.

**Comment by Olshansk** [comment]
@bryanchriswhite Does autoscaling (with staking validators) using k8s LocalNet + LibP2P work? https://github.com/pokt-network/pocket/tree/main/build/localnet#scaling-actors
