### ISSUE TITLE
[P2P] Churn Management and State Sync

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#357]
## Objective

Creating an issue to document the need for the `Churn Management` process in P2P to gather `PeerMetadata` information that allows the State Sync protocol to operate. 

**DISCLAIMER:** *The interface below may quickly get outdated, see `consensus/doc/PROTOCOL_STATE_SYNC.md` for the latest*

Specifically: 

```golang
type PeerSyncMeta interface {
	// the Public Key associated with the peer
	GetPeerID() string
	// the maximum height the peer has in the block store
	GetMaxHeight() int64
	// the minimum height the peer has in the block store
	GetMinHeight() int64
}
```
## Origin Document

[State_Sync_Protocol_Interfaces_And_Documentation](https://github.com/pokt-network/pocket/pull/342#discussion_r1019713374)

## Goals

- Enable state sync through a feature of P2P Churn Management

## Deliverable

- [ ] Implement an exchange of P2P Metadata during P2P Churn Management

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @andrewnguyen22

**Comment by jessicadaugherty** [comment]
Refactored
