### ISSUE TITLE
[Document] Claim/Proof Lifecycle and Merkle Tree Generation

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#358]
## Objective

Disseminate knowledge about the proof/claim lifecycle across the protocol team

## Origin Document

[Knowledge Transfer Requests](https://www.notion.so/pocketnetwork/Protocol-Team-83ea53817a944b99a6b5ec2d366a3b57)

## Goals

- Please document how the Claim/Proof Lifecycle and Merkle sum index tree algorithm generation works in V0 today. 

## Deliverable

- [ ]  2 pager on claim / proof lifecycle + merkle proof generation
    - [ ]  **Primary focus**: Claim / proof lifecycle
    - [ ]  **Secondary focus**: Merkle sum index tree algorithm generation

---

**Creator**: @jessicadaugherty

**Comment by andrewnguyen22** [comment]
https://github.com/pokt-network/pocket-core/pull/1507
