### ISSUE TITLE
[CLI] package it and create a binary named `p1`

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#366]
## Objective

Package the V1 CLI entrypoint into a package binary.

### Context

Instructions on installing the Pocket V0 CLI can be found [here](https://docs.pokt.network/node/tutorials/zero-to-node/software-install). The source code to the V1 CLI implementation can be found [here](https://github.com/pokt-network/pocket/tree/main/app/client/cli) but is not yet packaged into a binary.

### Example

The CLI today can be used by providing arguments to `go run app/client/*.go` from the source of the directory. A detailed flow and example is available here: here: https://github.com/pokt-network/pocket/pull/169.

### Naming

Our CNO (Chief Naming Officer) deliberated that the name should fittingly be `p1` 🙂

![image](https://user-images.githubusercontent.com/29378614/204847087-40fd1f86-e9ff-4784-aae0-6317193ec484.png)

## Goals

- Make sure that it's possible to execute the new `p1` binary locally
- Make it easy for developers to install the `p1` using `go` tooling

## Deliverable

- [ ] Update `Makefile` with new targets to build & install the client library
- [ ] Update any relevant github workflows to build, verify and update the packaged binary automatically
- [ ] Update any relevant documentation referencing the client binary

## Non-goals / Non-deliverables

- Any behavioural change in the codebase

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references

## Testing Methodology

- **Add**: Example of how `p1` works
- **All tests**: `make test_all`
- **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@Gustavobelfort We added some clarifying details here so it should be self explanatory, but let us know if not.

**Comment by Olshansk** [comment]
@Gustavobelfort I've reopened this ticket because I don't think it's fully done yet.

1. I, as an existing user, am not sure what I need to do to have the `p1` binary installed locally.
2. I, as an new user, do not know that the `p1` binary is available for me to use.

Could you update the documentation to reflect its existence and installation?

**Comment by Gustavobelfort** [comment]
> @Gustavobelfort I've reopened this ticket because I don't think it's fully done yet.
> 
> 
> 
> 1. I, as an existing user, am not sure what I need to do to have the `p1` binary installed locally.
> 
> 2. I, as an new user, do not know that the `p1` binary is available for me to use.
> 
> 
> 
> Could you update the documentation to reflect its existence and installation?
> 
> 

Sure! I will work on that 😄
