### ISSUE TITLE
[DOCUMENT] Interfaces for the M3 Fisherman Protocol

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#383]
## Objective

Code / document interfaces for the Fisherman Protocol to enable applications and sessions as well as better understanding around this piece of the M3 milestone.

## Origin Document

[ M3 Milestone ](https://github.com/pokt-network/pocket/blob/main/docs/roadmap/README.md#m3-pocket-ros-relay-or-slash)

[Utility Specifications](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#33-fisherman-protocol)

[Session Protocol Interface](https://github.com/pokt-network/pocket/pull/303)

[Portal QoS V2 Specification](https://miro.com/app/board/uXjVPkdmVMY=/) - please connect with PNI engineering when designing this interface.

This is the first step into beginning the Fisherman Protocol development.

## Goals

- Clear interface(s) that show the lifecycle of the fisherman protocol
- Clear documentation supporting the above

## Deliverable

- [ ] Coded interfaces
- [ ] Documentation support

## Non-goals / Non-deliverables

- Implementation of the interface

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Closing in place of the new approach outline [here](https://github.com/pokt-network/pocket/tree/main/utility/doc) for M3 task definition.
