### ISSUE TITLE
[DOCUMENT] Interfaces for the M3 Application Protocol

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#384]
## Objective

Define interfaces for the Application Protocol to interact with protocol actors and understand this piece of the M3 milestone. This is the first step into beginning the Application Protocol development.

## Origin Document

[ M3 Milestone ](https://github.com/pokt-network/pocket/blob/main/docs/roadmap/README.md#m3-pocket-ros-relay-or-slash)

[Utility Specifications](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#34-application-protocol)

## Goals

- Clear interface(s) that show the lifecycle of the application protocol
- Clear documentation supporting the above

## Deliverable

- [ ] Coded interfaces
- [ ] Documentation support

## Non-goals / Non-deliverables

- Implementation of the interface

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Closing in place of the new approach outline [here](https://github.com/pokt-network/pocket/tree/main/utility/doc) for M3 task definition.
