### ISSUE TITLE
[DOCUMENT] Interfaces for the M3 Governance Protocol

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#386]
## Objective

Define interfaces for the Governance Protocol to enable DAO-approved Fisherman as well as better understand how parameters work around this piece of the M3 milestone.

## Origin Document

[ M3 Milestone ](https://github.com/pokt-network/pocket/blob/main/docs/roadmap/README.md#m3-pocket-ros-relay-or-slash)

[Utility Specifications](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#38-governance-protocol)

This is the first step into beginning the Governance Protocol development.

## Goals

- Clear interface(s) that show the lifecycle of the governance protocol
- Clear documentation supporting the above

## Deliverable

- [ ] Coded interfaces
- [ ] Documentation support

## Non-goals / Non-deliverables

- Implementation of the interface

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

**Creator**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
Consult with PNF (Jack)

**Comment by Olshansk** [comment]
@jacklaing and I have discussed offline that PNF could provide a 1-2 pager on how they'd like V1 governance to work

**Comment by jessicadaugherty** [comment]
Thanks @Olshansk! PNF had mentioned a 1-2 pager re: a feature request but thought that was for V0. Are we sure they are clear on the deliverable(s) or do you want me to connect with their team?

**Comment by jacklaing** [comment]
I have both v0 and v1 feature requests. The v0 feature request is in some ways an MVP of the full v1 spec I had in mind.

**Comment by jessicadaugherty** [comment]
Perfect, thanks @jacklaing!

**Comment by Olshansk** [comment]
Closing in place of the new approach outline [here](https://github.com/pokt-network/pocket/tree/main/utility/doc) for M3 task definition.
