### ISSUE TITLE
[P2P] E2E Tests for p2p

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#39]
# Objective

Achieve a truly e2e-tested p2p

# Origin Document

P2P is unit tested and integration-tested through the aid of mocks. We are interested in having a real-life simulation mechanism at our fingertips, that we can create, destroy, monitor and control, to test how p2p nodes perform and interact in a truly distributed environment with real nodes.

The e2e test should spin containerized peers and have them perform random broadcasts and sends with assertion for each operation taking place, and testing results in the form of a report

# Deliverable
- [ ] A `make test_p2p_e2e` command to run a `docker-compose` enabled local e2e stack
- [ ] Documentation with instructions on how to :
  - [ ] create the e2e test
  - [ ] destroy the e2e test
  - [ ] [optional]monitoring the e2e test
  - [ ] [optional] Enable manual control of the broadcast progression
  - [ ] [optional] Enable automatic control of the broadcast progression
  - [ ] [optional] Enable the replay of the broadcast

The flags will help the e2e test to be smoothly runnable and controllable in CI environments.

# Owners

author/owner: @derrandz

**Comment by Olshansk** [comment]
@derrandz Do you think this could/should be closed in favour of https://github.com/pokt-network/pocket/issues/126 or should we keep it open as a separate issue?

**Comment by derrandz** [comment]
@Olshansk Agreed, kudos for suggesting Ghenkis and Cucumber.

**Comment by Olshansk** [comment]
Can't take credit for the idea. @iajrz and @luyzdeleon are using it for v0 and I figured we'd leverage the same thing.
