### ISSUE TITLE
[Tooling] Improve docker-compose stack (`make docker_wipe` and `make compose_and_watch`)

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#398]
## Objective

Improve DevX by making sure that we don't remove docker images/containers from other projects on the developer's machine.

`make docker_wipe` should not wipe everything but only Pocket v1 specific deployments

Also related: 
The stack in docker-compose takes the name from the containing folder:

![image](https://user-images.githubusercontent.com/29378614/207742679-2bb213d3-8286-4fdc-a90e-cd6014983e99.png)
![image](https://user-images.githubusercontent.com/29378614/207742706-e41f9de5-0de0-4b57-acfc-ee94ea5053de.png)

Perhaps we should name it `pocket` or something more meaningful.

## Origin Document

![image](https://user-images.githubusercontent.com/29378614/207744474-1a04a8ac-7e47-45fe-a0a7-78b6864b2d67.png)

Am I sure? It depends!

I think the assumption here would be: "yes, surely I am only removing stuff related to this project, not nuking everything otherwise the prompt would alert me"

## Goals

- Name the docker-compose deployment
- `make docker_wipe` should only wipe pocket related containers, images and volumes

## Deliverable

- [ ] Updated Makefile

## Non-goals / Non-deliverables

-

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: [@deblasis]
**Co-Owners**: [optional - github usernames of the co-owner(s)]

**Comment by Olshansk** [comment]
@Gustavobelfort Would you be willing to take this on?

**Comment by Gustavobelfort** [comment]
> @Gustavobelfort Would you be willing to take this on?
> 
> 

Sure !
