### ISSUE TITLE
[P2P] Add Connection Handshake functionality + Identity Check

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#41]
### Description
----
Implement the connections handshake process per the p2p specification

### Acceptance Criteria
----

- `.handshake()` authenticates connections and adds them to the connection pool on success
- `.handshake()` tracks which connection failed to authenticate for security purposes. (_file logs?_)
- `.handshake()` to take part of `inbound` and `outbound` socket opening.

### Deliverables
----

- `.handshake()` internal method to authenticate connections

----
##### Owners: @derrandz

**Comment by Olshansk** [comment]
Closing for housekeeping but may reopen in the future.
