### ISSUE TITLE
[P2P] Replace addressing via ServiceUrl/GenericParam with P2P routing

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#426]
## Objective

Offload the business logic of message routing entirely to the `P2P` module

We currently connect nodes using the endpoint (host & port) captured in an actor's `ServiceUrl`, which is retrieved/set using the `GenericParam` field in the proto. See #313 for the source of this naming and grep for `generic_param` in the codebase to find its uses. By default, we configure nodes to list on port 8080.

Hosts, ports and endpoint logic/complexity should be encapsulated inside the `P2P` module. No other modules, or configurations files (e.g. geneis et al) should have any understanding of network routing other than cryptographic identities.

## Origin Document

If you are taking on this task, make sure to read this discussion first: https://github.com/pokt-network/pocket/pull/403#discussion_r1060770345

## Goals

- Encapsulate network routing business logic to the `P2P` module
- Use cryptographic identities only for messaging, communication and configuration outside the `P2P` module
- Set up the codebase for integration with libp2p

## Deliverable

- [x] Address `TODO (#426):` in the codebase 
- [x] Refactor related code accordingly. Including but not limited to:
   - [x] Removing exposed P2P business logic (eg: `ActorToNetworkPeer`)

## Non-goals / Non-deliverables

-  [P2P] Peer Discovery - LibP2P - Consolidate Node/Peer ID with LibP2P Peer ID (#348)
-  [Utility] Design & implement a better approach to `GenericParam` /  `ActorSpecificParam` (#313)

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@deblasis  Made a few edits to the description so the scope is pretty clearly defined now.

**Comment by deblasis** [comment]
Thank you @Olshansk 🙏

**Comment by jessicadaugherty** [comment]
@jessicadaugherty and @bryanchriswhite investigate how much of this was accomplished through P2P refacotring and update or delete accordingly

**Comment by Olshansk** [comment]
@bryanchriswhite Can you review this ticket after merging in all the ongoing work, I think it'll be either resolved or no longer relevant.
