### ISSUE TITLE
[P2P] Refactor `CreateWithProvider` using the new `bus` based DI

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#429]
## Objective

Improve code-health and consistency of patterns

## Origin Document

While developing #402 and #331 I had to inject some dependencies into the `P2P` module. This was our first use case in our codebase and the initial approach was indeed marked as a `HACK` from the beginning but there was something missing that is now available via #425: the ability to register modules dynamically on the `bus` instance, effectively enabling Dependency Injection

This ticket was descoped from #425 which became quite large and scope-creepy:

https://github.com/pokt-network/pocket/pull/425#discussion_r1062837932

## Goals

- Remove the `CreateWithProviders` constructor and use the standardized `Create` instead.
- Refactoring the way we access the dependencies `AddrBookProvider` and `CurrentHeightProvider` by registering them at the caller site and consuming them inside the `P2P` `Create()`

## Deliverable

- [ ] Refactored `P2P` module `Create`
- [ ] Dependency injection for `AddrBookProvider` and `CurrentHeightProvider`

## Non-goals / Non-deliverables

- Changes in `P2P` logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis
**Co-Owners**: @Olshansk

**Comment by jessicadaugherty** [comment]
scope-creepy is my new favorite phrase haha
