### ISSUE TITLE
[LocalNet] Execution Height and Connection Errors

### ISSUE THREAD

**Issue by gokutheengineer** [pokt-network/pocket#433]
## Objective
I am experiencing the following unexpected behaviors when running LocalNet:

_Issue 1_. When LocalNet is run on main branch with the current commands in the README, and running the fresh LocalNet after executing the first `TriggerNextView` command and running `PrintNodeState` the height is printed as `2`, which is supposed to be `1`. 

_Issue 2_. Also, there is one other weird error I am receiving, but I am not sure if it is only on my setup. After doing few iterations of `TriggerNextView`,  `PrintNodeState`, and then `ResetToGenesis` one or some of the nodes refuse connections.

## Origin Document
Issue 1: 
<img width="1029" alt="Screen Shot 2023-01-08 at 11 33 45" src="https://user-images.githubusercontent.com/118421317/211195380-ce4e65e8-91cc-4727-94f3-31d19ac9084b.png">

Issue 2:
<img width="919" alt="Screen Shot 2023-01-08 at 15 57 52" src="https://user-images.githubusercontent.com/118421317/211197252-eb0d1ae5-79ce-4202-b6d4-542459cec267.png">

## Goals
- Identify the reason of the behavior and fix the problem (if exists)
- Enable smooth execution of LocalNet

## Deliverable
- [ ] LocalNet runs as expected

## Non-goals / Non-deliverables
- Change business logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @gokutheengineer 
**Co-Owners**:

**Comment by gokutheengineer** [comment]
> make db_drop && make docker_wipe_nodes

This command doesn't solve my issue, because I already execute make docker_wipe, before restarting the local net, which deletes the containers, images and volumes. I will investigate further.

**Comment by Olshansk** [comment]
Closed per @gokutheengineer's comment above 👌
