### ISSUE TITLE
[TECHDEBT] Update usages of `PersistenceRWContext` gov parameter accessors to use the more general `GetParameter()` function

### ISSUE THREAD

**Issue by h5law** [pokt-network/pocket#436]
## Objective

Update the different instances across `Persistence` and `Utility`, and anywhere else the `PersistenceRWContext` interface is used, to use the general `GetParameter(paramName string, height int64) (any, error)` function to access gov parameters.
 
This will include replacing the usages of `GetStringParam()`, `GetIntParam()` and `GetBytesParam()` and replacing them all with `GetParameter()` where this is appropriate. This is with the aim of reducing the code footprint across the modules affected.

Another part of this issue involves updating the logic of `GetParameter()` to automatically distinguish between `string` and `[]bytes` types given the `paramName` string. This must be done in a way that does not restrict the project from expanding the parameters without breaking the logic of this function.

## Origin Document

Since the merge of [PR#422](https://github.com/pokt-network/pocket/pull/422) the new generalised getter function `GetParameter()` has been implemented and has deprecated `GetBlocksPerSession()` and `GetServiceNodesPerSessionAt()`. However, all the other parameter accessor functions are not using this new generalised function yet.

## Goals

- Replace all gov parameter accessor functions using `GetStringParam()`, `GetIntParam()` or `GetBytesParam()` to use `GetParameter()`
- Update unit tests in `persistence/test/gov_test.go` and `utility/test/gov_test.go` to use the `GetParameter()` function
- Solve the issue around when to call the `[]bytes` variation of `GetParameter()` depending on the parameter name string

## Deliverable

- [ ] Update gov parameter accessors to use the `GetParameter()` function
- [ ] Update unit tests in `persistence/test/gov_test.go` and `utility/test/gov_test.go` to use the `GetParameter()` function where appropriate
- [ ] Update the logic of `GetParameter()` to detect `[]byte` types and distinguish them from `string` types automatically

## Non-goals / Non-deliverables

- [ ] Restrict the expansion of the gov parameters by adding specific type detection rules to `GetParameter()` that would inhibit parameter additions that don't follow the _current_ patterns.

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @h5law

**Comment by h5law** [comment]
@Olshansk what do you think of this outline? Is there anything I should change/add?

**Comment by h5law** [comment]
@Olshansk I have deprecated `GetStringParam()`, `GetIntParam()` and `GetBytesParam()` fully now. Replacing all uses across persistence and utility with `GetParameter()`. In order to solve the `[]byte` issue I initially thought adding type parameters to the `GetParameter()` function like
```go
GetParameter[int | string | []byte](paramName string, height int64) (any, error)
```
However, interface functions cannot have type parameters. So instead I added a few utility functions to the utility module (detailed below) to handle the conversion logic from `string` to `[]byte`.

All unit tests passing successfully. Happy to open a PR if this is all that is needed, so we can review the full list of changes.

In `utility/gov.go`

```go
func (u *UtilityContext) getByteArrayParam(paramName string) ([]byte, typesUtil.Error) {
	store, height, er := u.GetStoreAndHeight()
	if er != nil {
		return nil, er
	}
	value, err := store.GetParameter(paramName, height)
	if err != nil {
		return nil, typesUtil.ErrGetParam(paramName, err)
	}
	return typesUtil.StringToBytes(value.(string))
}
```

In `utility/types/util.go`

```go
func StringToBytes(s string) ([]byte, Error) {
	b, err := hex.DecodeString(s)
	if err != nil {
		return []byte{}, ErrStringToByteArray(err)
	}
	return b, nil
}
```

In `utility/types/error.go`

```go
const (
...
	CodeStringToByteArrayError            Code = 132
...
	StringToByteArrayError            = "an error occurred converting the string primitive to []byte"
)
...
func ErrStringToByteArray(err error) Error {
	return NewError(CodeStringToByteArrayError, fmt.Sprintf("%s: %s", StringToByteArrayError, err.Error()))
}
```

**Comment by Olshansk** [comment]
For future reference, the real origin document for this ticket is the discussion @h5law and I had here: https://github.com/pokt-network/pocket/pull/465#discussion_r1088095158

![giphy](https://user-images.githubusercontent.com/1892194/215879841-29e3327e-18be-4dcc-bae7-06e4c03e2b94.gif)

**Comment by h5law** [comment]
> Can we close this out as completed?

Yessir close the door on this one ✅
