### ISSUE TITLE
[Infra] Configuration Loader

### ISSUE THREAD

**Issue by iajrz** [pokt-network/pocket#44]
At present we are loading configurations from files exclusively. At some point we'll start adding flags to override specific configuration values.

A configuration loader should be written to make it so that flags are auto-generated in very much the same way configuration files can be automatically loaded by matching the Go structure to file contents.

This is low-burning at the moment, since configuration is in flux, but is part of the wiring milestone.

**Comment by Olshansk** [comment]
@iajrz I'm thinking of closing this out due to the lack of specific details / deliverables. Wdyt?

**Comment by Olshansk** [comment]
Closing per the comment above
