### ISSUE TITLE
[Core] Investigate memory leaks 

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#440]
## Objective

Make sure that we are not allocating memory without ever releasing it and other similar bugs that can lead to memory exhaustion.

## Origin Document

While investigating some instability in `LocalNet`, I have noticed that  some of the nodes were being killed for excessive memory pressure.

![image](https://user-images.githubusercontent.com/29378614/212942723-d12eff7a-a064-4a94-a8f6-372a46dcbc1b.png)

There might be several places where we should address this issue but as a starting point I have noticed that resetting to genesis via the debug CLI causes unwanted allocations.

In the video below, I focus on one of the nodes while I run multiple `ResetToGenesis` commands. Notice how the memory (top-right cell) increases in steps and then plateaus:

https://user-images.githubusercontent.com/29378614/212944742-a495685a-e4e2-4dd1-a156-79d760c80b90.mp4

## Goals

- Identify the root cause of the memory leaks
- Fix the memory leaks
- Identify if there are other areas of concerns in the codebase related to memory leaks and create follow-up tickets (e.g. an applied pattern that is a root cause that may present itself elsewhere in the codebase)

## Deliverable

- [ ] A working PR where multiple `ResetToGenesis` triggered sequentially do not cause node crashes anymore. 
- [ ] If other unrelated issues are identified along the way, please log them accordingly

## Non-goals / Non-deliverables

- Changes in the logic 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk, @gokutheengineer

**Comment by Olshansk** [comment]
@deblasis 

1. **Question**: Does `debug.FreeOSMemory()` fully solve this problem or just an improvement?

2. **Request**: Can you start a README on "debugging" and potentially add a make target with pprof (referenced in the README) so its easier for others to use in the future?

3. **Non-actionable comment**: Seems like hydrating the entire genesis state takes quite a bit of memory. Something to keep mental tabs on.

**Comment by deblasis** [comment]
> @deblasis
> 
> 1. **Question**: Does `debug.FreeOSMemory()` fully solve this problem or just an improvement?

It's an improvement that solves the problem. The optimal solution would be to figure out a way to reset to genesis `badger` and the `smt` with minimal deallocations-reallocations if that's even possible. 
That requires deeper investigation and I guess it's high weeds territory I will dive into while working on SavePoints and Rollbacks I guess.

> 2. **Request**: Can you start a README on "debugging" and potentially add a make target with pprof (referenced in the README) so its easier for others to use in the future?

On debugging potential memory leaks in general? 
I can certainly document the steps I followed to get to my conclusion if that helps.

> 3. **Non-actionable comment**: Seems like hydrating the entire genesis state takes quite a bit of memory. Something to keep mental tabs on.

Totally, at a glance, it seems that badger is the main memory-hogger, but yeah, it starts to become increasingly important now that we have to spin up more nodes locally. Mental tab open, pinned and bookmarked :)

**Comment by Olshansk** [comment]
> That requires deeper investigation and I guess it's high weeds territory I will dive into while working on SavePoints and Rollbacks I guess.

Makes sense.

> On debugging potential memory leaks in general?

Yea. We currently have the following in our `Makefile`:

```md
.PHONY: db_bench_init
db_bench_init: docker_check ## Initialize pgbench on local postgres - needs to be called once after container is created.
	docker exec -it pocket-db bash -c "pgbench -i -U postgres -d postgres"

.PHONY: db_bench
db_bench: docker_check ## Run a local benchmark against the local postgres instance - TODO(olshansky): visualize results
	docker exec -it pocket-db bash -c "pgbench -U postgres -d postgres"
```

So we could add a target that runs `pprof` as well.

> 
I can certainly document the steps I followed to get to my conclusion if that helps (where should I place it if that's the case?)

I think the two potential places could be `persistence/docs/README.md` or a new doc under `development/PROFILING.md`.

Having a starting point with something creates less friction for other people to add to it.

> Totally, at a glance, it seems that badger is the main memory-hogger, but yeah, it starts to become increasingly important now that we have to spin up more nodes locally. Mental tab open, pinned and bookmarked :)

🧠 📑

**Comment by deblasis** [comment]
@Olshansk 

> Yea. We currently have the following in our `Makefile`:
> 
> ```lisp
> .PHONY: db_bench_init
> db_bench_init: docker_check ## Initialize pgbench on local postgres - needs to be called once after container is created.
> 	docker exec -it pocket-db bash -c "pgbench -i -U postgres -d postgres"
> 
> .PHONY: db_bench
> db_bench: docker_check ## Run a local benchmark against the local postgres instance - TODO(olshansky): visualize results
> 	docker exec -it pocket-db bash -c "pgbench -U postgres -d postgres"
> ```
> 
> So we could add a target that runs `pprof` as well.
> 

I'll think about something / research for inspiration.

The problem is the interactivity of the process. Basically you need to:
- expose an endpoint that returns the collected metrics
- execute the flow that generates the unwanted memory usage spike/potential memory leak
- collect metrics from the aforementioned endpoint
- parse the dump file into pprof and also eventually comparing it with other previously collected dumps.

> I can certainly document the steps I followed to get to my conclusion if that helps (where should I place it if that's the case?)
> 
> I think the two potential places could be `persistence/docs/README.md` or a new doc under `development/PROFILING.md`.
> 
> Having a starting point with something creates less friction for other people to add to it.

💯
