### ISSUE TITLE
[UTILITY] Consolidate & refactor all utility messages

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#443]
## Objective

Prepare the codebase for adding the codebase for more complex Pocket specific business logic.

## Origin Document

As of [sha 9b7135](https://github.com/pokt-network/pocket/tree/9b7135031136fd7bff8eb2812db74dfa0d3a683b), a few places in the code contain duplicates of the same message.

For example, in `persistence/indexer/indexer_test.go`, we have:

```go
type MessageType int

const (
	SendMessage MessageType = iota + 1
	StakeMessage
	UnstakeMessage
	EditStakeMessage
	UnjailMessage
)
```

And in `utility/types/message.go`, we have:

```go
type Message interface {
	proto.Message

	SetSigner(signer []byte)
	ValidateBasic() Error
	GetCanonicalBytes() []byte
	GetActorType() coreTypes.ActorType
	GetMessageName() string
	GetMessageRecipient() string
}

var _ Message = &MessageSend{}
var _ Message = &MessageStake{}
var _ Message = &MessageEditStake{}
var _ Message = &MessageUnstake{}
var _ Message = &MessageUnpause{}
var _ Message = &MessageChangeParameter{}
var _ Message = &MessageDoubleSign{}
```

These need to be identified, consolidated and organized in a single place.

## Goals

- Identify all locations where duplicate messages are defined
- Make it easier to understand, easier to track and easier to build upon

## Deliverable

- [ ] A PR that consolidates all of these messages in one place
- [ ] Updated documentation explaining where/how these are used

## Non-goals / Non-deliverables

- Adding new functionality into the utility module 
- Fixing any bugs that may exist in the utility module
- Improving the readability and modularity of all of the existing code

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Olshansk

**Comment by jessicadaugherty** [comment]
@Olshansk check against cleanup 2/3 (find links)
