### ISSUE TITLE
[Tooling] Changelog verification date comparison

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#456]
## Objective

The current (39302d6, at time of writing) [changelog verification job](https://github.com/pokt-network/pocket/blob/main/.github/workflows/changelog-verify.yml) compares the date of the most recent version in the changelog against the current date. This causes CI runs to fail if a PR sits in review for long enough such that when the next commit triggers CI, it's the next day.

## Origin Document

This behavior was introduced in #397.

## Goals

- Improve developer experience by eliminating a common case of CI failures.

## Deliverable

- The CI job should compare against the date of the most recent commit in the PR branch which affected the relevant files, as opposed to the current date. 
- The existing pre-commit hook should remain functionally the same.

## Testing Methodology

- [x] Manual testing via `git` CLI.

### Objectives:

- Ensure pre-commit hook does not permit a commit without a version in the respective changelog with today's date (i.e. still works the same)
- Ensure GitHub actions passes on a branch where the changelog version **is not** the current date but does match the date of the most recent commit which modified the respective files.

### Methodology

1. Ensure pre-commit hook date verification still works:
    ```
    # Checkout new branch off of main for testing
    git checkout main
    git pull --ff-only
    git checkout -b test/changelog-verification
  
    # Create and stage new file to trigger changelog verification
    touch ./runtime/deleteme
    git add ./runtime/deleteme
    
    # Ensure pre-commit hook is setup
    # (see https://github.com/pokt-network/pocket/blob/main/docs/development/README.md#prepare-local-environment)
    
    # Expect changelog verification to fail on pre-commit
    git commit -m "should not see me in git log"
    ```
    ```
    Missing changelog in module: runtime/
    
    Changelog verification failed. See error messages for more detail.
    ```
1. Update respective CHANGELOG with a past date:
    ```
    # In runtime/docs/CHANGELOG.md
    ...
    [0.0.0.9] - 2023-01-22
    ...
    ```
    ```
    # Stage respective CHANGELOG changes
    git add runtime/docs/CHANGELOG.md
    ```
1. Ensure pre-commit hook date prevents committing with past date:
    ```
    # Expect changelog verification to fail on pre-commit
    git commit -m "should not see me in git log"
    ```
    ```
    Latest date in runtime/docs/CHANGELOG.md is incorrect.
    Latest: 2023-01-22, Current: 2023-01-23
    
    Changelog verification failed. See error messages for more detail.
    ```
1. Construct a commit and changelog entry with a past date:
    ```
    # Commit, ignore pre-commit hook, and set date(s) to the past
    GIT_COMMITTER_DATE="2023-01-22 12:00" git commit -n -m "past commit" --date="2023.01.22 12:00"
    ```
1. Push _(recommend to your own fork)_.
    ```
    git push <remote> HEAD
    ```
1. Open a PR and wait for the changelog verification job to run, it should pass.
---

**Creator**: @bryanchriswhite

**Comment by Olshansk** [comment]
1. TIL about `--ff-only`. I'm more of a `git pull --rebase` type of person, but can see the value in fast-forwarding to avoid unpredictable changes.

2. Fantastic explanation of the objectives, deliverables and testing methodology. Ty 👏

**Comment by Olshansk** [comment]
@bryanchriswhite One small NIT: Attach these sort of issues to M*:

![Screenshot 2023-01-23 at 12 16 34 PM](https://user-images.githubusercontent.com/1892194/214105577-820fbc53-7f7c-4f8e-ac76-f4378065fe47.png)
