### ISSUE TITLE
[Tooling][Proposal] changelog change group convention

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#461]
## Objective

I propose to establish a convention of "change groups", intended to supersede what I currently would identify as "unreleased version numbers" in our changelog files.

The current convention of "unreleased version numbers" don't seem to serve much purpose in their current usage other than to fit the schema such that you have a place to accumulate changes for the next release. I'm assuming that it follows, when the next release comes, that these unreleased version numbers will be consolidated into a single, actual, release version. If this is the case, then we would either have to replace the unreleased version numbers with something else, if we wanted to preserve the change groupings, or lose change groupings altogether. Regardless, there is still overhead in making these subsequent changes, in version control (i.e. requires code review, etc.), to each changelog containing unreleased versions as part of the release process. :grimacing: 

My interpretation of the point of separating unreleased changes from each other is to show which changes are (un)related. In my opinion, PR numbers (e.g. `#123`) would be a more pragmatic usage of this degree of freedom. I think a PR number would serve this purpose better in principal as it provides a reference (via its identity) to more information while also acting as a perfectly good change group delimiter. A PR number should also remove any perceived (and undue, IMHO) sanctity owed to the ordinality of the change groups, which may cause confusion or inconsistencies when attempting to resolve merge conflicts (see below). Lastly, PR numbers wouldn't need to be removed from the changelog at release, simplifying the release process and persisting the change groupings (~~for free~~ _complimentarily_).

## Origin Document

I'm noticing that when there is more than one PR open for a given module, there will almost necessarily be a merge conflict. An instance of this can be observed at the end of #450. When this happens the PR author will have to decide how to resolve the conflict and there isn't any documentation on how to navigate this yet, which could have a downstream impact on our process artifacts (e.g. changelogs, release notes, etc.).

## Goals

- Improve developer experience
- Improve parallel throughput of the team
- Reduce waste

## Deliverable

- [ ] Modify pre-commit and pre-push hooks to skip version comparison for unreleased versions
- [ ] Determine whether merge conflicts are still produced under this convention by the following scenario outlined in the  testing methodology section below.
- [ ] **If merge conflicts are still present in the workflow**, add a new section after  [docs/development/README.md > "Documentation Resources and Implementation"](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md#documentation-resources-and-implementation) which includes instructions on how to use the changelog, including handling the following merge conflict scenarios (for a single module's changelog):
  - ~~upstream has a newer date than the PR branch~~ (reduces to the last)
  - ~~upstream has an older date than the PR branch~~ ( " )
  - upstream has multiple change groups, one older and one newer than the PR branch (e.g. the first diagram)
- [ ] Migrate current changelogs (i.e. replace unreleased version numbers with PR numbers)  
  ```bash
  #!/bin/bash

  ### Changelog migration starter script...
  
  # Find all changelog files
  changelog_files=$(find . -type d -name "vendor" -prune -o -type f -iname "CHANGELOG.md" -print)
  
  # Iterate through each changelog file
  for changelog in $changelog_files; do
    echo "Processing $changelog"
  
    # List the unreleased versions
    versions=$(grep -oP '\[\K[0-9.]+(?=\])' "$changelog" | tac)
  
    for version in $versions; do
      echo "Version: $version"
  
      # Get the PR# for a given changelog version number
      commit_hash=$(git blame "$changelog" | grep "$version" | cut -f 1 -d " ")
      pr_number=$(git log -1 "$commit_hash" | grep -oP '#\d+')
  
      echo "PR#: $pr_number"
    done
  
    echo "-------------------------"
  done
  ```

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

### Merge conflict test
1. Note the name of the branch which implements change groups and create a new branch off of it: `git checkout -b temp/mock_main`. For the purpose of running our test, this will act as the main branch.
2. Add a new entry to the `pocket/app/docs/CHANGELOG.md` with an arbitrary (and/or fictitious) PR number and  **some past date**.
3. Create a new branch off of it `git checkout -b  temp/mock_pr`. This will act as the PR branch.
4. Add a new entry to the `pocket/app/docs/CHANGELOG.md` with an arbitrary (and/or fictitious) PR number and **some future date**.
5. Checkout `temp/mock_main` and add a new entry to the `pocket/app/docs/CHANGELOG.md` with an arbitrary (and/or fictitious) PR number and **today's date**.
6. Merge `temp/mock_main`: `git merge temp/mock_main`.
7. Is there a merge conflict?

  ```mermaid
  gitGraph
      commit
      branch "PR Branch"
      commit id: "[#456 - 2023-04-03]" type: HIGHLIGHT
      checkout main
      commit id: "[#123  - 2023-04-01]" type: HIGHLIGHT
      commit id: "[#789  - 2023-04-05]" type: HIGHLIGHT
      checkout "PR Branch"
      merge main
  ```
  (for comparison, the workflow prior to "change groups" which does produce merge conflicts, looks like this:)
  ```mermaid
  gitGraph
      commit
      branch FeatureA
      commit id: "[v0.0.0.1 - 2023-04-03]" type: HIGHLIGHT
      checkout main
      commit id: "[v0.0.0.1 - 2023-04-01]" type: HIGHLIGHT
      commit id: "[v0.0.0.2 - 2023-04-05]" type: HIGHLIGHT
      checkout FeatureA
      merge main
  ```

---

**Creator**: @bryanchriswhite

**Comment by jessicadaugherty** [comment]
Review above approach to changelog improvements @gokutheengineer @deblasis @Olshansk 

Alternative approach from @deblasis:
- Create text file named after PR number and put inside a folder (e.g. Changelogs)
- A job would pick up these files, aggregate them, and keep the Changelog after that
- Event that triggers this is merge to main

We should determine if we move forward with this current ticket as a first step in improving the Changelog and/or if we need a longer term overhaul.

**Comment by deblasis** [comment]
I just want to reiterate that I have nothing against @bryanchriswhite's changes per se, mine was more of a broader train of thought around our changelogs in general and since we are automating on top of them I wonder:

"What are we trying to achieve? Is having multiple changelogs the best possible approach?"

I imagine a world where (soon) Pocket V1 is live and we release often, in that world I envisage a single changelog with changes tagged by module perhaps. Why? Because ultimately if you have to convey the message: "we released these improvements: [list]" you have to collect these items anyway and you don't want to be jumping folders or clicking links just to see if P2P has been updated for example.

I was thinking about something like this (just an idea, there are certainly 10000 better ways):

```
[1.0.4.0] 2023-10-04

- [P2P] Improved Raintree redundancy - (PR #somenumber)
- [Telemetry] Fixed metric collection for Fisherman double-signing events - (PR #someothernumber)
- [Persistence] Implemented decentralized stateblockmerklefishergatesyncsavepointpicker - (PR #totallymadeup)

```
This file would be autogenerated when we merge PRs to `main`

@jessicadaugherty 
> Alternative approach from @deblasis:
> 
> * Create text file named after PR number and put inside a folder (e.g. Changelogs)
> * A job would pick up these files, aggregate them, and keep the Changelog after that
> * Event that triggers this is merge to main

I am just capturing this here for future discussions but I agree with what we said during the planning meeting that this is would be low priority even if the team agrees on the approach. For now, let's stick to our guns.

The above could be achieved by doing something like what the folks @ Hashicorp are doing in this popular tool: https://github.com/hashicorp/consul

I know because I thought I wanted to join them so I contributed, etc but then I got interested in Web3 and I bumped into Pocket :) 

Specifically:
## - The folder
![image](https://user-images.githubusercontent.com/29378614/214690473-f34ea53f-b09e-4720-9428-001badb8306d.png)
## - Inside the folder
![image](https://user-images.githubusercontent.com/29378614/214690589-5faaa7b7-04cf-4321-8b79-8e3b0ae3c5d9.png)
## - A changelog
![image](https://user-images.githubusercontent.com/29378614/214690640-0935c69d-a945-43ef-b0e2-2a0f4a854d85.png)
## - The workflow that checks if a changelog is used
![image](https://user-images.githubusercontent.com/29378614/214690781-3ff991c6-9729-441c-bea0-375ae281876f.png)
## - The workflow logic
![image](https://user-images.githubusercontent.com/29378614/214690816-2cc0002b-d6a0-4702-a87f-41b7a40ac963.png)
## - How it looks like in a PR (aka no conflicts with other devs)
![image](https://user-images.githubusercontent.com/29378614/214691320-4aaa2825-74d5-485e-9bbd-db6deb7226e7.png)
## - Contributing documentation
https://github.com/hashicorp/consul/blob/b357ec9e203d746f7182ed7dd2eab9236cd6d822/docs/contributing/add-a-changelog-entry.md
## - The release scripts
![image](https://user-images.githubusercontent.com/29378614/214691878-cf435204-b5b5-400a-8a92-084f29cdc94a.png)
https://github.com/hashicorp/consul/blob/f0a9b301742ed88f92d7760457eb4e8fff9f45fe/build-support/scripts/release.sh
![image](https://user-images.githubusercontent.com/29378614/214692216-375bcf80-0c3d-4e2c-bb64-4fa2deb249a2.png)

**Comment by jessicadaugherty** [comment]
Thank you @deblasis for the amazing feedback.

> Because ultimately if you have to convey the message: "we released these improvements: [list]" you have to collect these items anyway and you don't want to be jumping folders or clicking links just to see if P2P has been updated for example.

Makes a lot of sense.

> I agree with what we said during the planning meeting that this is would be low priority even if the team agrees on the approach. For now, let's stick to our guns.

Leaning this way as well. The scope @bryanchriswhite laid out is small so it would be worth prioritizing if this small step does result in faster time to code changes. It sounds like you don't think there will be much time savings here at the moment though, @deblasis?

**Comment by Olshansk** [comment]
The current approach isn't great but just "good enough" and doesn't  slow us down much. 

I'd argue it forces the developer (us) to simply see what changes we made in each module, summarize it, and evaluate if it was necessary.

This is going to be more important  when we have a live TestNet and external node runners will want to see (in one place) what the changes were.

I propose that we move this out into M4 and evaluate & develop a proper solution then. 👍?

**Comment by deblasis** [comment]
@jessicadaugherty I agree with @Olshansk, the current approach is good enough, we noted that there's some friction thanks to @bryanchriswhite and we captured this discussion for the benefit of all. 

If a PR came in anyway from @bryanchriswhite or anyone else we'd have to accept the improvement I guess, that's the beauty of Open Source. So, @bryanchriswhite if you feel strongly about it, just do it, nobody can stop you :) 
I did that when there was something that was frustrating me (first iteration of config and genesis management).

At the latest (M4) this issue will come up again and given the priorities we'll have then, we can always reassess.

This is where my mind is at, regardless, this is great teamwork 🙏

**Comment by jessicadaugherty** [comment]
Sounds good, all! Refactoring for M4 and moving to the backlog to be revisited in the future. Thanks for starting the discussion @bryanchriswhite!

**Comment by jessicadaugherty** [comment]
Considering for bounty @Olshansk @bryanchriswhite

**Comment by Olshansk** [comment]
> Considering for bounty @Olshansk @bryanchriswhite

I think that's reasonable once we define **exactly what** we want to do, but that requires some brain cycles from the core team.

@bryanchriswhite I know you've been thinking about deeply. If/when you have time (no pressure and no urgency), feel free to update the deliverables/requirements and we can take it from there.

**Comment by jessicadaugherty** [comment]
10-4 @Olshansk! 

@bryanchriswhite based on existing criteria and pending any modifications recommending we bump this to an M (1 full day of work) per:

>  Migrate current changelogs (i.e. replace unreleased version numbers with PR numbers)

There are 38 version in the Utility changelog alone. This task is not hard but the effort is tedious.

**Comment by bryanchriswhite** [comment]
@jessicadaugherty :grimacing: Indeed the migration bit seems a bit rough at this point if done completely manually. I added a detail about how to get the PR# from a given changelog & version number. :mechanical_arm: That should be a healthy leg up on automating the hard part. (:mechanical_leg:) 

In addition to that snippet, one would could collect all the changelog programatically like so (a quick chatGPT query later): `find . -type d -name "vendor" -prune -o -type f -iname "CHANGELOG.md" -print`. I think this would get any contributor picking this up, well on their way to automating the migration.

**Comment by Olshansk** [comment]
@bryanchriswhite Can you update the details/guidelines in the github description with the details and just add the `community` label when you think its ready?

**Comment by 3scava1i3r** [comment]
Is this available right now?I wish to pursue the same

**Comment by Olshansk** [comment]
> Is this available right now?I wish to work on the same,recommended by @h5law

Potentially (I can sync with @bryanchriswhite). Would you be open on something I would deem as a higher priority / importance? 

Example: #494

We also have some other work we are looking for help on regarding tooling (e.g.related to logging):

<img width="779" alt="Screenshot 2023-06-14 at 11 20 49 PM" src="https://github.com/pokt-network/pocket/assets/1892194/6d4d079c-005e-4942-a16a-fffe45634c5c">

Would you be up for either of those?

**Comment by 3scava1i3r** [comment]
@Olshansk thank you so much for the swift response,I would require some more context on the same but I'll work on it asap✨

**Comment by Olshansk** [comment]
Closing this out as changelogs are not being used at the moment.
