### ISSUE TITLE
[Tooling] Re-evaluate all log Msgf calls

### ISSUE THREAD

**Issue by Gustavobelfort** [pokt-network/pocket#479]
## Objective

Reevaluate all `msgf`log calls into explicit log labels. 

Example Usage:

Before:

```go
u.logger.Info().Msgf("CreateAndApplyProposalBlock - computed state hash: %s", stateHash)
```

After:
```go
u.logger.Info().Str("state_hash", stateHash).Msg("Successfully computed state hash")
```

## Origin Document

- The following comment from the PR that introduced logging in the codebase: https://github.com/pokt-network/pocket/pull/420#discussion_r1072533121

<img width="893" alt="Screenshot 2023-01-30 at 7 00 23 PM" src="https://user-images.githubusercontent.com/1892194/215651941-2869a29c-db05-4dba-a9f8-48111ef96355.png">

## Goals

- Improve log readability and aggregation in logging tools such as `Loki`.
- The new labels should be easily distinguishable from other variables and functions.

## Deliverable

- [ ] All `msgf`log calls should be converted into explicit labels with clear and descriptive names.

## Non-goals / Non-deliverables

- The changes should not affect the functionality of the code.
- Adding new logs

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Gustavobelfort 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Closing this out as unplanned for the foreseeable future. Ticket can be reopened if/when needed.
