### ISSUE TITLE
[Keybase] HashiCorp Vault support as a keybase backend

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#527]
## Objective

Add a more node-operator-oriented, production-ready backend for the keybase.

## Origin Document

The implementation for the CLI & keybase are available at [app/client](https://github.com/pokt-network/pocket/tree/main/app/client) but only supports a filesystem-based key based backed by [BadgerDb](https://github.com/dgraph-io/badger). Example from `/Users/olshansky/workspace/pocket/pocket/app/client/cli/account.go`:

```go
	// Open the debug keybase at the specified path
	pocketDir := strings.TrimSuffix(dataDir, "/")
	keybasePath, err := filepath.Abs(pocketDir + keybaseSuffix)
	// ...
	kb, err := keybase.NewKeybase(keybasePath)
	// ...
```

PNI and other major node runners make use of [HashiCorp Vault](https://www.vaultproject.io/) which makes it a great 1st candidate for an alternate keybase backend.

<img width="760" alt="Screenshot 2023-02-20 at 9 06 16 AM" src="https://user-images.githubusercontent.com/1892194/220167118-6d804b9c-98ef-4896-91df-050c220c59ad.png">

## Goals

- Leverage the existing keybase utilities & interfaces for production uses cases
- Make TestNet keybase management easier for PNI and other node operators
- Add support for [HashiCorp Vault](https://www.vaultproject.io/) as a keybase backend

## Deliverable

- [ ] A PR that enables using Valut as a backend for keybase management
- [ ] A flag or configuration allowing the user to specify which backend they want to use via the CLI
- [ ] A document explaining how to setup HashiCorp Vault as a backend

## Non-goals / Non-deliverables

- Adding new commands to the CLI
- Modifying the core node business logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Add a README w/ relevant documentation & [mermaid](https://mermaid-js.github.io/mermaid/) diagrams on how to use this for keybase management

## Testing Methodology

- [ ] Instructions (e.g. a demo) with a video and list of commands showing the functionality in action
---

**Creator**: @Olshansk 
**Co-Owners**: @h5law @okdas @jessicadaugherty

**Comment by jessicadaugherty** [comment]
If this is in M4, does that mean it's a priority to include in testnet @Olshansk?

**Comment by Olshansk** [comment]
> If this is in M4, does that mean it's a priority to include in testnet @Olshansk?

Not a blocker for starting TestNet, but will make it more efficient, simpler and easier to incorporate external node runners (e.g. if we do an incentivized TestNet).

Might be a good alternate to https://github.com/pokt-network/pocket/issues/194#issuecomment-1437484939 but will keep thinking of other starter tasks too.

**Comment by jessicadaugherty** [comment]
Great, thank you @Olshansk!

**Comment by jessicadaugherty** [comment]
Hey @Olshansk can you provide an effort for this? Seems S-M but want to confirm.

**Comment by Olshansk** [comment]
> Hey @Olshansk can you provide an effort for this? Seems S-M but want to confirm.

I think the effort to test & integrate it with HashiCorp is a fair amount of infra work: making it easy through documentation or tools for other to get set up. I set it as an `L`
