### ISSUE TITLE
[CONSENSUS] Validators crash after setting pacemaker to auto with docker-compose localnet.

### ISSUE THREAD

**Issue by 0xBigBoss** [pokt-network/pocket#530]
## Objective

Running through the [localnet setup](https://github.com/pokt-network/pocket/blob/main/docs/development/README.md#L166), the optional step 8 crashes the validators after around 20 blocks. https://gist.githubusercontent.com/0xBigBoss/1a2b9d20597ffe4efdc7d1fe3ca491ed/raw/428ef0132743714e963174c84714e35dc0aadaf2/pocket%2520v1%2520docker%2520compose%2520crash%2520log

```
node1.consensus   | panic: runtime error: invalid memory address or nil pointer dereference
node1.consensus   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc54a28]
node1.consensus   | 
node1.consensus   | goroutine 1 [running]:
node1.consensus   | github.com/jackc/pgx/v5/pgxpool.(*Conn).connResource(...)
node1.consensus   | 	/go/src/github.com/pocket-network/vendor/github.com/jackc/pgx/v5/pgxpool/conn.go:121
node1.consensus   | github.com/jackc/pgx/v5/pgxpool.(*Conn).Conn(...)
node1.consensus   | 	/go/src/github.com/pocket-network/vendor/github.com/jackc/pgx/v5/pgxpool/conn.go:117
node1.consensus   | github.com/jackc/pgx/v5/pgxpool.(*Conn).Exec(0xf428b5?, {0x10bdda8?, 0xc0000380b8?}, {0xc081325c50?, 0x3?}, {0x0?, 0xa98695?, 0xdf9160?})
node1.consensus   | 	/go/src/github.com/pocket-network/vendor/github.com/jackc/pgx/v5/pgxpool/conn.go:83 +0x28
node1.consensus   | github.com/pokt-network/pocket/persistence.connectToDatabase(0xc0003a8a50)
node1.consensus   | 	/go/src/github.com/pocket-network/persistence/db.go:104 +0x3ca
node1.consensus   | github.com/pokt-network/pocket/persistence.(*persistenceModule).NewReadContext(0xc0003a8fd0, 0x18)
node1.consensus   | 	/go/src/github.com/pocket-network/persistence/module.go:160 +0x31
node1.consensus   | github.com/pokt-network/pocket/consensus.(*consensusModule).getValidatorsAtHeight(0xc081580d70?, 0xc06e62d900?)
node1.consensus   | 	/go/src/github.com/pocket-network/consensus/helpers.go:312 +0x5e
node1.consensus   | github.com/pokt-network/pocket/consensus.(*consensusModule).didReceiveEnoughMessageForStep(0xc060cd6900, 0x60cd6900?)
node1.consensus   | 	/go/src/github.com/pocket-network/consensus/helpers.go:141 +0x2d
node1.consensus   | github.com/pokt-network/pocket/consensus.(*HotstuffLeaderMessageHandler).HandleNewRoundMessage(0x8000101?, 0xc060cd6900, 0x0?)
node1.consensus   | 	/go/src/github.com/pocket-network/consensus/hotstuff_leader.go:38 +0x15e
node1.consensus   | github.com/pokt-network/pocket/consensus.(*consensusModule).handleHotstuffMessage(0xc060cd6900, 0xc081778540)
node1.consensus   | 	/go/src/github.com/pocket-network/consensus/hotstuff_handler.go:50 +0x556
node1.consensus   | github.com/pokt-network/pocket/consensus.(*consensusModule).HandleMessage(0xc060cd6900, 0xf5ee4e?)
node1.consensus   | 	/go/src/github.com/pocket-network/consensus/module.go:321 +0x14f
```

## Origin Document

The validators should not crash.

## Goals

Validators should stay online even under heavy load.

## Deliverable

- [ ] Identify the source of the issue
- [ ] Resolve the issue  

## Non-goals / Non-deliverables

TBD

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: https://github.com/0xBigBoss
**Co-Owners**: [optional - github usernames of the co-owner(s)]

**Comment by Olshansk** [comment]
Moving this into our upcoming iteration. Thinking @deblasis could potentially pick it up given that he's in the code.

cc @jessicadaugherty.

**Comment by 0xBigBoss** [comment]
Just tried again in https://github.com/pokt-network/pocket/pull/578 and it's still an issue.

**Comment by deblasis** [comment]
Thank you for the additional context @0xBigBoss ! I still haven't looked into this at all but I am changing a lot of stuff in utility, consensus and persistence, a fix might come out of that work.
 
I am going to ping you and give you a heads-up when I believe that is fixed. Thanks also for your patience 🙏

**Comment by Olshansk** [comment]
> Thank you for the additional context @0xBigBoss ! I still haven't looked into this at all but I am changing a lot of stuff in utility, consensus and persistence, a fix might come out of that work.
> 
> I am going to ping you and give you a heads-up when I believe that is fixed. Thanks also for your patience 🙏

Just as a heads up that I start working on this in #592.  I thought I could get this one done quickly, but need to look deeper. 

I realized that the external contribution we got for pooling (#407) wasn't quite complete, so I need to refactor how we manage our connections.

@0xBigBoss If you have more explicit (e.g. specific num of blocks, or time spent) to repro the issue, would definitely help.

**Comment by 0xBigBoss** [comment]
> @0xBigBoss If you have more explicit (e.g. specific num of blocks, or time spent) to repro the issue, would definitely help.

@Olshansk So after I send `TogglePacemakerMode` and `TriggerNextView` using the docker compose localnet, it typically crashes in under 10 seconds and usually before height 20. I don't think I've seen it get past height 20. Just tried again on latest main.

I also don't know how to reproduce the `sorry, too many clients already`. I haven't seen it again.

**Comment by Olshansk** [comment]
Up for review at #592 now

**Comment by Olshansk** [comment]
PR moved to #627 per the comment here: https://github.com/pokt-network/pocket/pull/592#issuecomment-1486026417
