### ISSUE TITLE
[P2P] TCP Connection Pooling (Earliest Recently Used, Last Recently Used Push Queue)

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#54]
# Objective

Achieve an efficient connection pool to minimize TCP roundtrips that come with establishing new connections.

# Origin Document
When a connection pool is full, and we need to pool new connections, some space has to be made so some existing pooled connections must be "evacuated".

In order to efficiently use the connections' pool, we need some pool re-ordering logic. A suggestion is to use something similar to the RAM's LRU (_Last Recently Used_) algorithms, that will evacuate the oldest unused connection in the pool, by always queueing first the most recently used connection, making the last position in the queue, the oldest unused connection in the pool, the one to be evacuated.

# Deliverables

- [ ] Implement a limited-size connection pool with re-ordering logic:
   - [ ] The pool must provide methods to retrieve specific questions by address
   - [ ] The pool must provide evacuate unused connections when new connections are wanting to be pooled to make space for them.
   - [ ] The pool must not interrupt an on-going pooled connection in favor of a to-be-made connection.

# Owners
---
author/owner: @derrandz

**Comment by Olshansk** [comment]
Closing for housekeeping but may reopen in the future.
