### ISSUE TITLE
[P2P] Basic transport security

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#544]
## Objective

Ensure transport-level encryption is enabled and required by default for all network participants.

The initial implementation of transport security should be compatible with the current formulation of V1 identity, this may be as simple as using the crypto helpers introduced in #534 together with [go-libp2p's `p2p/security/tls` package](https://pkg.go.dev/github.com/libp2p/go-libp2p@v0.26.0/p2p/security/tls). 

## Origin Document

![image](https://user-images.githubusercontent.com/600733/221156912-1c792fb3-3761-44cd-b8f0-1410f6c5156d.png)

## Goals

- P2P network peers support, and **require**, TLS with their counterparts.
- TLS configuration prefers a [GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode) variant of AES for symmetric encryption to optimize for speed and security.

## Deliverable

- [ ] ...
- [ ] A PR that enables configuring TLS security using hard-coded test fixtures
- [ ] Document the testing methodology in the source code so its repeatable (Bonus: automate)
- [ ] Unit tests for bad/unavailable certificates when turned on (Bonus: E2E tests)

## Non-goals / Non-deliverables

- Configuring remote infrastructure (i.e. DevNet/TestNet) to have certificates automatically available
- Changing any identity or crypto types and/or interfaces
- Manipulating X509 certificate(s) / chain(s)

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

1. Setup testing environment, following [development docs](https://github.com/pokt-network/pocket/tree/main/docs/development)
1. `docker exec -it node1.consensus ash` (see: [SO post](https://stackoverflow.com/questions/39362730/how-to-capture-packets-for-single-docker-container/61855965#61855965))
    1. (in container) `ip a`, note IP address
    2. (in container) `cat /sys/class/net/eth0/iflink`, note the "interface number"
    3. <Ctrl+d> or `exit` to exit the container shell
    4. (back on the host) `ip link|grep <INTERFACE_NUMBER>`, note the interface name, e.g. (if interface number was `55`, name would be `vetha165c5f@if54`):
        ```
        55: vetha165c5f@if54
        ```
1. Repeat 1.1-1.3 for `node2.consensus` container
1. Open wireshark (may need escalated privilege to see desired network interfaces)
1. Select the interface matching `node1.consensus`
1. Filter the captured packets by the IP matching `node2.consensus`
1. Look for a packet which has the `PSH` flag set
1. Inspect the `Data` contained in the package to see if any cleartext is readable (e.g. protobuf types: `...type.googleapis.com/consensus.HotstuffMessage...`)

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @bryanchriswhite

**Comment by Olshansk** [comment]
Love the details in the testing methodology. I added some deliverables/non-goals. Check them out when you have a chance

**Comment by jessicadaugherty** [comment]
May be done by default. Please confirm by going through testing methodology @bryanchriswhite

**Comment by bryanchriswhite** [comment]
It looks like this indeed may be taken care of by default when using libp2p. 

1. The [docs do say](https://pkg.go.dev/github.com/libp2p/go-libp2p#New):

    > If no security transport is provided, the host uses the go-libp2p's noise and/or tls encrypted transport to encrypt all traffic;
1. Packet capturing seems to corroborate this, see below:

## Before ([packet capture dump](https://drive.google.com/file/d/1e4VTtHlrDEtkQpEAZJ06SQWVFZFVHnUy/view?usp=sharing))
![localnet_clear](https://user-images.githubusercontent.com/600733/226562885-dc3bcd08-f467-41c1-a28c-cf1dab5d1f14.png)

## After ([packet capture dump](https://drive.google.com/file/d/1--slV6EjCre5HaMIjFAC441fztmhkuDD/view?usp=sharing))
![localnet_opaque](https://user-images.githubusercontent.com/600733/226562892-2ed0c014-8530-4277-a82b-32fd34d9555c.png)

**Comment by bryanchriswhite** [comment]
Based on packet inspection, it looks like libp2p is preferring noise but I haven't dug into that part of libp2p's code yet to see the details for myself.

Outstanding concerns:

- [ ] Ensure that nodes **require** encrypted transport; i.e. they refuse connections from peers which aren't using encrypted transports

**Comment by Olshansk** [comment]
Thanks @bryanchriswhite! Wanted to share a few TILs along with som questions

----

> Packet capturing seems to corroborate this:

TIL the word `corroborate` 😅 

---

I haven't done packet inspection and according to GPT, it's still the best tool out there. Found it pretty surprising no better UI has come along.

![Screenshot 2023-03-21 at 10 50 57 AM](https://user-images.githubusercontent.com/1892194/226698098-e1db069f-4103-4516-a294-bc86b37c0fc0.png)

---

I wasn't familiar with Noise so I read about it for a bit.

**Fun fact**: just one individual designed the whole thing. http://noiseprotocol.org/noise.html#introduction

1. Does this use the private key of the node to initiate the handshake before we have a symmetric key?
2. My understand is that `Noise` is a framework rather than a protocol, so is the only difference that we're not leveraging 509 certificates (which we don't have anyhow) in the case of permissionless nodes?

**Comment by Olshansk** [comment]
@bryanchriswhite Appreciate the thorough research, investigation and response. Makes sense to me and I think it's definitely more than enough for what we need from a practical standpoint. This is good context to have if we ever end up needing to debug and dive deeper.
