### ISSUE TITLE
[P2P] Buffered writes with Chunks Ordering + Buffered Reads with Bytes Reordering

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#55]
# Objective
---

Implement bytes chunking/re-ordering for data streams.

# Origin Document
---

When dealing with large payloads, the p2p module should be able to split the payload into a series of ordered chunks, and stream them to the recipient, such that if the ordered of receipt is flipped, the recipient can re-order the chunks based on their metadata, thus retrieve the large data in full after the stream has ended or a end of message delimiter is encountered in the stream.

# Deliverables
---

- [ ] A small IO library to be used in the read and write loops of the pooled connections, to: 
  - [ ] provide chunking functionality for large payloads before send
  - [ ] provide re-ordering and unchunking functionality for large payloads on receipt

# Dependencies:
---

This effort requires that https://github.com/pokt-network/pocket/issues/86 be successfully implemented.

# Owners
---
author/owner: @derrandz

**Comment by Olshansk** [comment]
Closing for housekeeping but may reopen in the future.
