### ISSUE TITLE
[Telemetry] Build Devnet Dashboard

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#551]
## Objective

Create a public-facing Devnet dashboard using Grafana to track primary Utility KPIs (relays, rewards, txs, latency, etc.).

## Origin Document

[Dashboard Research](https://www.notion.so/pocketnetwork/Devnet-Dashboard-Research-and-Design-Recommendations-f88a3debfc2446119a1360b36bd631b1)

[Dashboard Wireframes](https://miro.com/app/board/uXjVPzSHo5A=/)

<img width="611" alt="Screenshot 2023-03-07 at 12 27 33 PM" src="https://user-images.githubusercontent.com/1892194/223544632-f9a12ecd-7d46-4278-a63c-cbf32d648478.png">

Sources of data to enable these dashboards include:
- Logging
- Metrics
- Trees (key-value stores using BadgerDB)
- PostgresDB

## Goals

- Enable the community to understand the state and progress of Devnet development
- Improve the Devnet UX by creating an at-a-glance dashboard that provides insights into the performance of network utility
- Create a foundation on which to get new ideas & suggestions for what the dashboard (easier when there's something to poke holes at)
- Enable unpacking the data in the `BlockHeader` protobuf

## Deliverable

- Build a Devnet Grafana dashboard that includes the following visualizations and interactivity:
	- 6 main tiles:
		- [x] Block #
		- [x] Block Timestampt
		- [x] Actor counts: Apps, Servicers, Validators, Fisherbeings, Portals
		- [ ] Rewards - past X hours (total across all pools and actor types)
		- [ ] Relays - past 24 hours (does not exist yet)
	- 3 tables (tabbed; filter by column values, sortable by column ascending/descending values)
		- [x] **Nodes**: ActorType, Address, ServiceURL, Balance, Paused (Y/N), StakeAmount (NA or amount)
		- [x] **Apps**:  Address, Stake
	    - [ ] **Transactions**: Block #, TxType, Hash, serialize (or deserialized?) data type
    - [ ] A placeholder for RelaysTable
- Identify what data cannot be included in the first version of the dashboard and:
	- [ ] Create issues for future iterations of the dashboard
	- [ ] Create issues for interfaces or missing data access points
- Documentation on:
	- [ ] How to run this dashboard locally
	- [ ] How to add new components to the dahboard

### Keep in mind

Things to keep in mind while building this for future iterations of the dashboard:
- Filtering rewards by type: validator, servicer, fishermen, etc...
- Viewing relay numbers over N hours (modifieable)
- Viewing report cards
- **Relays Table**: RelayChainID, # relays 24 hrs, # staked apps per RelayChainID

### Protos for reference

```proto
message BlockHeader {
  uint64 height = 1;
  string networkId = 2;
  string stateHash = 3;
  // ... 
  bytes proposerAddress = 5;
 // ...
  google.protobuf.Timestamp timestampt = 7;
}

message Actor {
  ActorType actor_type = 1;
  string address = 2;
  string public_key = 3;
  repeated string chains = 4;
  string service_url = 5; // Not applicable to `Application` actors
  string staked_amount = 6;
  int64 paused_height = 7;
  int64 unstaking_height = 8;
  string output = 9;
}
```

## Non-goals / Non-deliverables

- A pixel perfect dashboard accounting for all pocket utility
- Showing actual relay numbers on the dashboard (just something to plug into)
- Building usage or other health-related dashboards

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references

---

**Creator**: @jessicadaugherty
**Co-owner**: @Olshansk  @okdas

**Comment by jessicadaugherty** [comment]
@Olshansk ready for review

**Comment by Olshansk** [comment]
Just so it doesn't get lost, some additional inspiration: https://beta.pokt.info/

**Comment by okdas** [comment]
Had great progress on this. The app is hosted in https://github.com/pokt-network/v1-explorer-dev repo. Going to focus on this ticket for the reminder of the iteration.

**Comment by Olshansk** [comment]
> Had great progress on this. The app is hosted in [pokt-network/v1-explorer-dev](https://github.com/pokt-network/v1-explorer-dev) repo. Going to focus on this ticket for the reminder of the iteration.

Thanks for the update Dima!

**Request**: Would be great to add some more visuals (gif, video, link to a dev instance) in the v1-explorer-dev repo! Consider even creating a ticket just to upgrade that documentation and making sure its accessible from our wiki: https://github.com/pokt-network/pocket/wiki

**Comment by okdas** [comment]
Here's how the dashboard looks so far:

<img width="1749" alt="image" src="https://github.com/pokt-network/pocket/assets/4950477/97346839-1539-45d3-9b21-f2e257492ea4">

**Comment by okdas** [comment]
> Would be great to add some more visuals (gif, video, link to a dev instance) in the v1-explorer-dev repo! 

Yes, absolutely! This project has been relatively small; however, I am confident that I will continue to maintain it as a central hub that not only serves as a dashboard but also provides links to documentation, grafana dashboards (which are pre-populated with correct variables, allowing for easy access to metrics and logs), and other relevant information.

> Consider even creating a ticket just to upgrade that documentation.

One of the deliveries of that ticket is creating more tickets, so yes - they're coming!

**Comment by Olshansk** [comment]
> Here's how the dashboard looks so far:
> 
> <img alt="image" width="1749" src="https://user-images.githubusercontent.com/4950477/245660175-97346839-1539-45d3-9b21-f2e257492ea4.png">

You should share it with the team on discord too! Looks like a great starting point!
