### ISSUE TITLE
[P2P] Simplify P2P module implementation

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#553]
## Objective

Simplify the libp2p module implementation by refactoring the Transport and Network interfaces. 

## Origin Document

Next steps identified in #500

## Goals

- Reduce the complexity of the `Transport` and `Network` interfaces

## Deliverable

- [ ] Refactor the `Transport` and `Network` interfaces to improve readability
- [x] Consider renaming the `Network` object to better reflect its behavior as a Router but keep in mind that it may be replaced with a "raintree pubsub router" in future iterations

## Non-goals / Non-deliverables

- Adding new functionality to the LibP2P integration 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty
**Co-owner**: @bryanchriswhite

**Comment by jessicadaugherty** [comment]
@bryanchriswhite @Olshansk this is ready for review

**Comment by bryanchriswhite** [comment]
Looks good to me 👍
