### ISSUE TITLE
[P2P] Remove "legacy" P2P module & rename libp2p module directory

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#554]
## Objective

Remove the legacy P2P module and rename the libp2p module directory and object names for clarity, while also simplifying the P2P module interface and cleaning up technical debt in the debug CLI and node startup.

## Origin Document

Next steps identified in https://github.com/pokt-network/pocket/pull/500

## Goals

- Remove unneeded legacy p2p module (`./p2p`)
- Improve libp2p clarity by renaming the module directory and object names (`./libp2p`)
- Simplify the p2p module interface by removing unnecessary or redundant code to improve maintainability
- Cleaning up technical debt in the debug CLI and node startup

## Deliverable

- [ ] Code associated with the legacy P2P module is removed from the codebase
- [ ] Libp2p module directory and associated object names are renamed to reflect their functionality and improve code clarity
- [ ] The p2p module interface is simplified and unnecessary or redundant code is removed.
- [ ] Technical debt introduced in the debug CLI and node startup is cleaned up
- [ ] Updated p2p documentation to reflect the module changes

## Non-goals / Non-deliverables

- Adding new features or changing functionality to p2p business logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty
**Co-owner**: @bryanchriswhite

**Comment by jessicadaugherty** [comment]
@bryanchriswhite @Olshansk this ticket is ready for review

**Comment by bryanchriswhite** [comment]
I would purpose rewording the last goal to be more like the last part of the objective statement to avoid ambiguity around *which* technical debt:

> cleaning up technical debt in the debug CLI and node startup

In this case, the techdebt comments in the changes made to those specific places are representative of some simplification that can be done at this stage which we don't want to forget (but probably won't).

**Comment by jessicadaugherty** [comment]
Tysm @bryanchriswhite - updated!
