### ISSUE TITLE
[P2P]: Convert P2P Wire Codec to Protobuf

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#57]
# Objective
---

Use protobuf as the one and only codec for communication, and deprecate the wire codec in favor of Protobuf.

The baseline functionality of the wire codec should be satisfied with protobuf. Wire Codec provides functionality that enables three important behaviors:

 - Ability to peak into the received payload size without allocating memory, allowing for validation logic to reject the payload size if too big.
 - Ability to determine if the received payload is an error.
 - Ability to determine the order of received packets. (_Useful when data is chunked_).

# Origin Document
---

P2P uses wire_codec to guarantee connection metadata exchange before any send/receive takes place. The wire codec helps encode into the wire payload the following information:

 * Size
 * Is Error?
 * Is EOF?
 * Is Encoded?
 * The Payload

It's important to use the wire_codec so that connections can know how many bytes to read, the meaning of these bytes, and how to decode them. This is very important when we are dealing with an open connection that continually sends a series of messages.

We are interested in deprecating wire_codec in favor of a more standarized approach, more specifically using protobuff.

# Goals
---

- [ ] Deprecate the wire codec in favor of protobuff
  - [ ] Use protobuff to encode and decode all messages
  - [ ] Use a protobuff wrapper message with metadata fields to replace the wire codec's metadata
  - [ ] Refactor the read/receive operation to read up to a delimiter and use this delimiter to mark end of message (_Check the following [bufio method](https://pkg.go.dev/bufio#Reader.ReadString)_)

# Pre-requisites
---

The way protobuf decoding typically works is that: 
  - memory is allocated prior to decoding
  - bytes are decoded into the message type whose memory was allocated.

 
Protobuf must provide functionality to 'peak' into data to retrieve size without allocating memory prior, to properly replace the wire codec and providing the same functionality.

Previous research regarding this is available at the following [document](https://www.notion.so/WireCodec-vs-Flatbuffers-vs-Protocol-Buffer-for-wire-byte-encoding-14bae15b5a784e74a1b6b1e237e43a0a). This research did not attend to the possibility of using `Any.pack` and `Unpack` as a way to avoid allocating memory, so feel free to look into that.

An importat [issue](https://github.com/pokt-network/pocket/issues/70) to help in the research. (_Please act on the actionables on the issue when research is done_)

**Comment by Olshansk** [comment]
@derrandz I think we can likely close this one since we'll end up going with Pre2P as the main P2P module, but then transferring both the code & learnings from the original P2P module to handle IO, muxing, etc... Wdyt?

**Comment by derrandz** [comment]
@Olshansk Good point.
