### ISSUE TITLE
[E2E] E2E test harness with LocalNet

### ISSUE THREAD

**Issue by dylanlott** [pokt-network/pocket#580]
## Objective

The first step to developing our E2E test suite is to get the minimal harness that wires together all the right pieces and starts the documentation for everything. This ticket is for that minimal initial harness and documentation.

Should roughly use a LocalNet cluster to spin up a cluster-manager node and call commands on that node since it is primed as a validator already. This approach should allow us the flexibility to swap out Kubernetes planes underneath the E2E tests without any changes.

## Origin Document

#466 

## Goals

- Integrate with the LocalNet in a way that can be easily extended to DevNet
- Create the harness for writing and developing with E2E tests on LocalNet
- Allow creation of pod resources from the E2E tests themselves.

## Deliverable

- [ ] Run Gherkin tests against LocalNet that can run pocket binary calls.
- [ ] Documentation outlining what the E2E tests do, how to write new ones, and how they work under the hood.

## Non-goals / Non-deliverables

- Writing a full network simulator
- Writing a comprehensive test suite
- Integrate CI/CD with the E2E tests

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make test_e2e`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @dylanlott

**Comment by Olshansk** [comment]
@dylanlott I looked at the deliverables & non-goals of this ticket and its unclear to me what the exactly THIS ticket will deliver.

For example: It says that "writing a comprehensive test suite" or "integrating it into our CI/CD pipeline" are non-goals, so what will the document contain?

**Comment by dylanlott** [comment]
Closing, addressed by #644
