### ISSUE TITLE
[E2E] ArgoCD integration

### ISSUE THREAD

**Issue by dylanlott** [pokt-network/pocket#581]
## Objective

When code is merged to specific branches or when pull requests with specific labels are opened against main, the E2E tests should run on DevNet. These tests may also be triggered manually but continuous testing and integration will be important to developing a solid foundation of tests. Integration with Github from ArgoCD should be investigated as well.

## Origin Document

#466 has a non-goal of CI/CD integration. This ticket covers the scope cut out of the original ticket.

## Goals

- Configure ArgoCD to run E2E tests as part of merges to specific branches or pull requests made with a specific label.
- Allow manual local trigger of E2E tests on DevNet.

## Deliverable

- [ ] Tests are run in ArgoCD when merges are made to main or pull requests against main are opened with a specific label.

## Non-goals / Non-deliverables

- Writing additional tests
- Modifying existing tests
- Running E2E tests every time we make a tiny documentation change.

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make test_e2e`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @dylanlott

**Comment by Olshansk** [comment]
@dylanlott How many tests did you have in mind for this ticket, is it just the `help` command?

**Comment by dylanlott** [comment]
This ticket doesn't care about any test coverage, only about adding E2E test runs to ArgoCD on specific Githuh events e.g. a merge to main being deployed on DevNet, triggering a run of E2E tests once the deployment is green.

**Comment by jessicadaugherty** [comment]
Redundant. Believed to be different tasks but covered by #582
