### ISSUE TITLE
[Core, Tooling] upgrade to go 1.20.x

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#588]
## Objective

Upgrade the version of  golang that we use in the repo to the  latest stable version of the 1.2 major version branch.

## Origin Document

![image](https://user-images.githubusercontent.com/600733/225300219-987d8f47-3794-4537-af30-119d3e6d84b4.png)

## Goals

- Minimize future upgrade friction
- Enable new native features (e.g. stdlib multi-error support)

## Deliverable

- [x]  Update go version in the repo & debug any issues which arise.
- [x] Update go version in infrastructure code (e.g. [Dockerfile(s)](https://github.com/pokt-network/pocket/blob/main/build/Dockerfile.localdev#L1), k8s manifest(s)/template(s), etc.)
- [ ] Replace usage of `go.uber.org/multierr` to use `err.join` (https://stackoverflow.com/a/74645028/768439)

## Non-goals / Non-deliverables

- Refactoring outside the scope of debugging any issues encountered.

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)

## Testing Methodology

- [ ] Updated version should be reflected in the [go.mod](https://github.com/pokt-network/pocket/blob/main/go.mod#L3)
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@bryanchriswhite I added this to iteration 13 and added removing uber's multierr as a dependency.

**Comment by Olshansk** [comment]
Completed by @okdas and @dylanlott in the prior iteration.
