### ISSUE TITLE
[Cleanup] Style consistency with explicit return values

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#59]
Example:
In `GetPoolAmount`, we have named return values but still return values explicitly.
In `GetAllPools`, we have named return values that we make use of.

There is variation and inconsistency and, so I prefer that we stick with one (whichever that is). My preference is to avoid return values per the suggestion here: https://dave.cheney.net/practical-go/presentations/gophercon-israel.html#_avoid_named_return_values

Note: just leaving this one comment but applies to all the actors.

_Originally posted by @Olshansk in https://github.com/pokt-network/pocket/pull/42#discussion_r838851664_

There is a backlogged protocol hour for this discussion exactly. 

The actionable is to refactor all functions to follow consistent style ruling. This spans over all modules

**Comment by Olshansk** [comment]
Closing for now as this is a low priority and we do not have an explicit style guide yet. This can be automated / validated in the future with the automation @okdas has done.
