### ISSUE TITLE
[Testing] Organizing test utilities package(s)

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#609]
## Objective

Agree on a convention which we can document that establishes where to put common test code for reuse between packages.

## Origin Document

![image](https://user-images.githubusercontent.com/600733/227213624-1d0ab993-006b-4d76-bdf4-a75d1e61c4d2.png)

## Goals

- Agree on a conventional place to organize test utilities packages (e.g. `pocket/internal/testing`)
- Support de-duplication of test code across packages (i.e. test util pkgs are importable )
- Ensure test packages are excluded from non-test builds (e.g. using build constraints: `//go:build test`)

## Deliverable

- [x] Document testing utils package location somewhere ([contributing](https://github.com/pokt-network/pocket/tree/main/docs/contributing), [development](https://github.com/pokt-network/pocket/tree/main/docs/development), wiki?)
- [x] Add testing utils package; start by moving `prepareDNSResolverMock()` from `pocket/module_raintree_test.go` (post #576)

## Non-goals / Non-deliverables

- Identifying additional duplication
- Refactoring unrelated test code

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] Ensure test util package members are not present in symbol table of non-test builds:
  1. `go build -o ./pokt-node ./app/pocket`
  2. `nm ./pokt-node | grep prepareDNSResolverMock` should print nothing
      If `prepareDNSResolverMock` was included in the build, it will be listed in the symbol table which we can print with `nm`. **Double-check the function names match, a typo could result in a false positive**. Additionally, one can build a test binary (`go test -c -o <output bin path> [-run <test func name>] <pkg>`) on a test/pig which is known to import a test util function and ensure that it is present in the symbol table, as a control.

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @deblasis

**Comment by Olshansk** [comment]
@bryanchriswhite Just wanted to follow up with some additional context

1. Fully support this idea. It was always the plan but just never a priority.
2. Example: We copy-paste our functions similar to `basePersistenceMock` for mocking, which should 💯 % be shared in a common location.
3. We have some shared prod related utilities in `shared/utils/*` so `shared/testing/*` could follow the same pattern (for now).
4. In #379, @Gustavobelfort started implementing a standard go file structure (i.e. using `internal` where appropriate), but we never finished it. The initial approach can be found in #412.
5. I want to know what we're documenting!

![Screenshot 2023-03-23 at 12 35 12 PM](https://user-images.githubusercontent.com/1892194/227331270-142824a0-2e44-4a96-b69d-b6498ecfca87.png)

**Comment by bryanchriswhite** [comment]
@Olshansk Haha - yea, I must have gotten distracted. Thanks for calling this out! :raised_hands: Sentence finished. :heavy_check_mark: :wink: 

Thanks for the links! :raised_hands: I read through to [golang-standards/project-layout](https://github.com/golang-standards/project-layout/tree/master/internal) which (is a great resource - thanks for sharing) and describes `/internal` like so:

> Private application and library code. This is the code you don't want others importing in their applications or libraries. Note that this layout pattern is enforced by the Go compiler itself. See the Go 1.4 [release notes](https://golang.org/doc/go1.4#internalpackages) for more details. Note that you are not limited to the top level internal directory. You can have more than one internal directory at any level of your project tree.

I would argue that given the convention, would better communicate our intention to put cross-package test code in an `internal` pkg. It would seem that it doesn't matter where that `internal` package lives; i.e., it gets the same treatment from the compiler and should be interpreted the same by humans. If you feel strongly about being downstream from `/shared`, which I can understand, I think `/shared/internal` or `/shared/internal/testing` could be a nice compromise.

**Comment by bryanchriswhite** [comment]
It also looks like [build tags/constraints](https://pkg.go.dev/go/build#hdr-Build_Constraints) have changed since the last time I looked:

> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.

...

> A build constraint, also known as a build tag, is a condition under which a file should be included in the package. Build constraints are given by a line comment that begins
>
> ```
> //go:build
> Build constraints may also be part of a file's name (for example, source_windows.go will only be included if the target > operating system is windows).
> ```
>
> See 'go help buildconstraint' (https://golang.org/cmd/go/#hdr-Build_constraints) for details.

**Comment by Olshansk** [comment]
@bryanchriswhite Should this ticket be in the `Done` state?
