### ISSUE TITLE
[Infrastructure] Dev cluster observability infrastructure migration

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#612]
## Objective

The infrastructure team is going to retire the company-wide hosted Grafana instance, and we've been asked to deploy the observability stack we need on dev cluster locally.

## Goals

- Let protocol developers get insight into protocol infrastructure

## Deliverable

- [x] Deploy Grafana, Metrics and Logging solution
- [x] Document new infrastructure
- [x] Update [existing information](https://www.notion.so/pocketnetwork/V1-networks-7d95c10c930c45c3823c871f21d44fca?pvs=4#468618dfd8304336ab5a58f4f264091e) about observability infra

## Non-goals / Non-deliverables

- We don't need highly available infrastructure for our purposes (not yet) so this can be done quickly - no need to spend time on complex solution 

## General issue deliverables

- [ ] Update any relevant local/global README(s)

## Testing Methodology

- [ ] Let any protocol dev to log in and view dashboard/metrics/logs

---

**Creator**: @okdas

**Comment by Olshansk** [comment]
@okdas Thanks for linking to the notion doc for in the 3rd deliverable. Was wondering if you could also link out to the READMEs you plan on updating for the "Grafana, Metrics & Logging" solutions? Sould be easy to find in https://github.com/pokt-network/pocket/wiki

**Comment by Olshansk** [comment]
> @Olshansk this is going to be covered in [pokt-network/protocol-infra](https://github.com/pokt-network/protocol-infra) repo (Documentation WIP in open PR), but that it a good idea to add information about devnets to pocket wiki as well, noted.

These details are definitely worth adding in the github issue description.

**Comment by okdas** [comment]
This is probably not visible as work is happening in closed repo, but I've got this implemented – need to test/adjust and will update docs right after.

**Comment by okdas** [comment]
I think I'm done with that, will work with the greater Infra team to review/merge this work on Monday.

**Comment by okdas** [comment]
This has been done.
