### ISSUE TITLE
[P2P] Raintree address index search bug

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/pocket#617]
## Objective

Fix a bug in the raintree implementation and make tests sensitive to regression.

## Origin Document

![image](https://user-images.githubusercontent.com/600733/227503095-5d886935-cab9-4634-895d-97ca2625ab65.png)

![image](https://user-images.githubusercontent.com/600733/227503282-1eabbae3-983d-40cc-9f70-468348e5def9.png)

## Goals

- Improve test coverage of the raintree implementation
- Improve correctness of the raintree implementation

## Deliverable

- [ ] Add regressions test(s) (i.e. fails on `main` pre-merge) which assert that each address is seen once as a routing target 
- [ ] Add "alphabet" test(s) (see: `p2p/raintree/peers_manager_test.go`) to make sure that add/remove preserve the ring-like structure
- [ ] Add "alphabet" test(s) which have offset `addrList`s (i.e. doesn't start with `A`) and asserts that each address would be contacted
- [ ] Update the address list binary search to split the list where the sort "wraps around" to search each separately

## Non-goals / Non-deliverables

- Refactoring un-related P2P module package members

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @deblasis @Olshansk

**Comment by bryanchriswhite** [comment]
I'm curios to understand if these log lines from localnet have anything to do with this bug (potentially part of the testing methodology):

```
node4.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT messages;Cbyzantine optimistic threshold not met: (1 > 2.67?) kind=REPLICA module=consensus                           
node1.consensus  | 11:17AM level=INFO ⏳?Waiting ⏳for morenHOTSTUFF_STEP_COMMIT mess=gas; byzantine optimistic threshold not met: (1 > 2.67?) kind=REPLICA module=consensus                           node2.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT t_ssages; byzantine optimistic threshold not met: (1 > 2.67?) kind=R_PLICA module=consensus                         ev
node3.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT messages; byzantine optimistic threshold not met: (1 > 2.67?) kind=LEADER module=consensus   
```

**Comment by Olshansk** [comment]
> I'm curios to understand if these log lines from localnet have anything to do with this bug or if that's expected behavior (potentially applicable to testing methodology):
> 
> ```
> node4.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT messages; byzantine optimistic threshold not met: (1 > 2.67?) kind=REPLICA module=consensus
> node1.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT messages; byzantine optimistic threshold not met: (1 > 2.67?) kind=REPLICA module=consensus
> node2.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT messages; byzantine optimistic threshold not met: (1 > 2.67?) kind=REPLICA module=consensus
> node3.consensus  | 11:17AM level=INFO ⏳ Waiting ⏳for more HOTSTUFF_STEP_COMMIT messages; byzantine optimistic threshold not met: (1 > 2.67?) kind=LEADER module=consensus
> ```

Nothing to do with this bug. The timeouts happen because the consensus engine is not on "automatic mode" by default.

See what happens here when its automatic: https://github.com/pokt-network/pocket/pull/592

**Comment by bryanchriswhite** [comment]
> Nothing to do with this bug. The timeouts happen because the consensus engine is not on "automatic mode" by default.
> 
> See what happens here when its automatic: #592

@Olshansk Is "automatic mode" synonymous with "pacemaker mode" here?

Sorry for not adding more context originally; those log lines were **extracted from the middle of a pacemaker mode run** in my localnet and are quite reproducible in my experience. Apologies for also perhaps burying the lead; I was more interested in highlighting and understanding the meaning behind the **`byzantine optimistic threshold not met: (1 > 2.67?)`** portion of the message.

**Comment by Olshansk** [comment]
> @Olshansk Is "automatic mode" synonymous with "pacemaker mode" here?

Yes, that is correct.

> Apologies for also perhaps burying the lead; I was more interested in highlighting and understanding the meaning behind the byzantine optimistic threshold not met: (1 > 2.67?) portion of the message.

You will likely need to download and zoom in and out on different parts of this image, but lmk if it answers your question.

![Screenshot 2023-03-27 at 1 28 35 PM](https://user-images.githubusercontent.com/1892194/228059480-a1d26bd8-0184-4795-8490-27c4fbe957eb.png)
