### ISSUE TITLE
[Infrastructure] Add helm charts to localnet

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#625]
## Objective

Improve the deployment and maintenance process of the Pocket Network Protocol by implementing Helm Charts, while maintaining the option to revisit Operators in the future for custom configurations.

## Origin Document

[Devnet Demo - Protocol Hour 2023/03/23
](https://www.notion.so/pocketnetwork/9e0590bdbd754163a5e7905f2246892c?v=ad14b5c982384c99944b153692c18f33&p=b7f50da7f67648ec82e86a98b63266b5&pm=s)

## Goals

- Develop Helm Charts for the Pocket Network Protocol deployment that streamline configuration management and reduce deployment time.
- Create a versioning system to manage the Helm Charts in the deployment repository, allowing for easy updating and rollback capabilities.
- Ensure that the Helm Charts implementation is flexible enough to accommodate the potential future use of Operators for custom configurations.

## Deliverable

- [x] Helm Charts for the Pocket Network Protocol deployment, including templates, values, and other necessary configuration files.
- [x] A versioning system in the infrastructure repository to manage Helm Chart updates and releases, along with clear documentation on how to update or roll back to a specific version.
- [x] Ensure PVCs are deleted on scale down

## Non-goals / Non-deliverables

- Further work on operators

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by okdas** [comment]
Note to myself – make sure PVCs are deleted on scale down.

**Comment by Olshansk** [comment]
> Note to myself – make sure PVCs are deleted on scale down.

Should we add it as a deliverable for this ticket? Feel free to edit and add it in if so!

**Comment by jessicadaugherty** [comment]
Reviewing notes from last week's sync and the above comments I have added these to the deliverables @okdas 

> - Add localnet-like Init container to wait for psql
> - Ensure PVCs are deleted on scale down

**Comment by jessicadaugherty** [comment]
Removed "add localnet-like init container to wait for psql" AC as it is completed per https://github.com/pokt-network/pocket-operator/issues/18 

Thanks!

**Comment by okdas** [comment]
All tickets related to that issue have been merged.
