### ISSUE TITLE
[CONSENSUS] Create helper in consensus tests for waiting for FSM events

### ISSUE THREAD

**Issue by gokutheengineer** [pokt-network/pocket#634]
## Objective

Create a helper function for waiting for FSM events in consensus tests. 

## Origin Document

![Error](https://user-images.githubusercontent.com/118421317/228469706-c92ae00a-1cd8-4cfd-9639-adac295f684c.png)

## Goals

- Ensure state sync tests show deterministic behavior.

## Deliverable

- [ ] Helper function `WaitForFSMEvents` for consensus tests.

## Non-goals / Non-deliverables

- Change business logic

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @gokutheengineer 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@gokutheengineer I think this is a priority over leader election.

It could also be good candidate for the "shared testing utilities" @bryanchriswhite is working on.

**Comment by Olshansk** [comment]
As we will likely be removing the FSM, I'm closing this out for now
