### ISSUE TITLE
[Infra] `cluster-manager` should not stake validators that are already staked in genesis at startup

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#635]
## Objective

Improve DevX and reduce the errors that are expected but that can create confusion, especially for newcomers.

## Origin Document

While pairing, @gokutheengineer and I noticed that right after `make localnet_up` the logs in Tilt show some error messages:

![image](https://user-images.githubusercontent.com/29378614/228504938-09733513-3735-4dfc-9117-60ad788b6e69.png)

after a quick investigation, it turned out that:

- `v1-validator001` was trying to broadcast messages to other validators that were not yet online
- The messages that `v1-validator001` was trying to broadcast were the `stake` transactions for the validators that were coming up online but that are already part of genesis (the first four validators):
![image](https://user-images.githubusercontent.com/29378614/228506116-c8da024e-f770-4b74-9bce-ee227a1e9077.png)

## Goals

- Reduce friction and errors that can be avoided since they can confuse and slow down development

## Deliverable

- [ ] update `cluster-manager` to not stake validators 001..004 at start

## Non-goals / Non-deliverables

- Changes in logic apart from `cluster-manager`

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @gokutheengineer

**Comment by Olshansk** [comment]
@deblasis If there's an opportunity to also improve the logs (e.g. the validator may still potentially be coming online, please retry in x seconds), please do so. Use your best judgment if it provides value
