### ISSUE TITLE
[Infra] sometimes inconsistent behaviour when scaling up validators in localnet

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#636]
## Objective

Address inconsistent behaviour in `Localnet` when scaling up validators.

`make localnet_down` should "destroy everything" to ensure that the developer can rollback to a clean slate state consistently.

## Origin Document

While pairing, @gokutheengineer and I discovered that even if we were running the same commands locally, we ended up with inconsistent behaviour.

Essentially even if I ran a `make localnet_down`, when I scaled up to 5 validators, Tilt logged that it was, to quote:

> Attaching to existing pod (v1-validator005-0). Only new logs will be streamed.

![image](https://user-images.githubusercontent.com/29378614/228509851-8cab5460-94e5-4a93-97a6-13849066e05e.png)

Also, when trying to broadcast messages it looked like if this "resumed" pod was in an inconsistent state, returning unexpected errors about database tables

![image](https://user-images.githubusercontent.com/29378614/228509977-0c708936-75b0-4ced-aefa-7859a6f28245.png)

## Goals

- Ensure that developers can rollback to a clean slate state consistently in Localnet
 
## Deliverable

- [ ] Updated Tiltfile and/or other manifests

## Non-goals / Non-deliverables

- 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @gokutheengineer, @okdas

**Comment by Olshansk** [comment]
I'll look into this with @okdas in the next iteration. 

This concerns the postgres schema being removed after we have created a new validator.

Fwiw, after we scale to 5 validators and do `localnet_down`, I do expect everything to scale back up to 5 because that it was the integrity of the database has unless we `resetToGenesis`.

**Comment by Olshansk** [comment]
> PostgreSQL schema is never deleted when validators are scaled down from 5 to 4.

When we create a new schema, we populate it with the genesis data, followed by new blocks.

If we stake a new validator at height N, we DO NOT copy over the trees to schema from someone at a higher height.

This is what state sync (@gokutheengineer) is working on.

There are several elements at play here, so I will look into this in a future iteration.

**Comment by Olshansk** [comment]
@okdas Let us know if you've started looking into this or have any new thoughts/update. I will aim to dive deeper mid next week.

**Comment by jessicadaugherty** [comment]
Check on this after cluster manager and helm chart work is completed to see if this is still an issue @okdas

**Comment by jessicadaugherty** [comment]
Some things were fixed. Some things weren't. But it's unclear what is left to be fixed. Closing this issue in favor of creating issues reported as they are found.
