### ISSUE TITLE
[Core] Align on `Create` function structure

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#642]
## Objective

Create a deterministic and consistent way of how each module's `Create` factory function signature should look.

## Origin Document

See the discussion [here](https://github.com/pokt-network/pocket/pull/623/files/9f74aff1ba72b8ae0eb530c84be6331ed73bac43..2df31e07448f908114628098ab5006dca0e8afe1#r1149013569)

<img width="710" alt="Screenshot 2023-03-29 at 8 43 17 PM" src="https://user-images.githubusercontent.com/1892194/228723231-5fde2d02-2345-4ce4-8844-b1a73fa6380f.png">

<img width="713" alt="Screenshot 2023-03-29 at 8 43 26 PM" src="https://user-images.githubusercontent.com/1892194/228723227-61d945ff-b8e8-4723-91bc-48a294422441.png">

## Goals

- Designing the most idiomatic way (w.r.t to Pocket and Go) on how the `Create` method signature should look
- Make the factory functions across the codebase consistent
- Make it clear and easy for new devs to the codebase to create new modules

## Deliverable

- [ ] Updated documentation in `shared/modules/doc/README.md` on how to `Create` modules
- [x] Update all modules with a `Create` function based on the new standards

## Non-goals / Non-deliverables

- Any business logic modifications

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite

**Comment by Olshansk** [comment]
@bryanchriswhite Why did we reopen this?

**Comment by bryanchriswhite** [comment]
I wasn't positive that the PR which closed it satisfied all the deliverables. I think we may still need to update some docs. I thought "rescope" would be appropriate for that.

**Comment by Olshansk** [comment]
> I wasn't positive that the PR which closed it satisfied all the deliverables. I think we may still need to update some docs. I thought "rescope" would be appropriate for that.

Can you submit a PR that updates the docs started by @deblasis on modules when you have a chance? With that in place, I think we'll satisfy the requirements of this ticket.

**Comment by jessicadaugherty** [comment]
**Iteration 15 Planning:** Updated estimate
