### ISSUE TITLE
[P2P] Consolidate the socket module with the rest of the repository by implementing `Module` interface for the p2p socket.

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#66]
### Objective

To unify modules' style across the repository.

### Origin Document

The socket component in the p2p module is an internal p2p component, however following on the footsteps of Consensus, we will implement the `Module` interface for the socket, as was done with the leader election and sortition components in Consensus.

We sacrificing access-modification (_keeping these components bounded to their modules and private_) to achieve code uniformity.

### Deliverables

- [ ] Update the `p2p/socket.go` to implement the `Module` interface at `shared/modules/module.go`

### Owners

@derrandz

**Comment by Olshansk** [comment]
@derrandz Can we close this out as "wont do" since it's no longer applicable?

**Comment by Olshansk** [comment]
Closing per the discussion at https://github.com/pokt-network/pocket/issues/61#issuecomment-1151545332
