### ISSUE TITLE
[Infra] Switch DevNets to utilize Helm chart

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#674]
## Objective

We now have a Helm chart that powers LocalNet. We should utilize the same chart for DevNets, which allows sharing the same infrastructure code between different networks.

## Origin Document

- Unblocks automatic e2e tests on DevNets
- Stabilizes infrastructure
- Allows to iterate on infrastructure by changing the charts in `pokt-network/pocket` repo.

## Deliverable

- [x] Create Applications for as a part of `v1-network-base` helm chart - https://github.com/pokt-network/protocol-infra/tree/main/charts/v1-network-base
- [x] Make sure `cluster-manager` and `cli-client` work as expected 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
- [ ] ***k8s LocalNet**: verify a `k8s LocalNet` is still functioning correctly by following the instructions [here](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md)

---

**Creator**: [github username of the creator]
**Co-Owners**: [optional - github usernames of the co-owner(s)]

**Comment by jessicadaugherty** [comment]
Thanks for getting this one going, Dima!
