### ISSUE TITLE
[Persistence] Module First Implementation

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket#68]
Owner @andrewnguyen22 
Co-Owners: @iajrz  @Olshansk 

End Date May 1, 2022

## Objective

Create the first iteration of the Pre-Persistence module and integrate it with the other modules within the /github.com/pokt-network/pocket codebase

## Deliverables

Minimally implement the first iteration of the persistence layer.

- Create clean interfaces and MVP schemas for the P2P dataset, Consensus dataset, Mempool dataset, and the State dataset
- Use PostgreSQL as the first 'Database Engine'
- Minimally implement the State Versions Deduplication Strategy
- Minimally implement the Immutable State Schema (Patricia Merkle Tree) and AppHash functionality
- Integrate the DB Engine into the development infrastructure stack
- Integrate the persistence module with the other modules, deprecating pre-persistence

**Comment by andrewnguyen22** [comment]
TODO need milestone to attach

**Comment by Olshansk** [comment]
Being worked on in https://github.com/pokt-network/pocket/pull/73

**Comment by Olshansk** [comment]
Closing with PR73 merged.
