### ISSUE TITLE
[P2P] Standardize cryptographic conversion math

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#69]
### Objective

To standardize the mathematical conversion from ed25519 to curve25519 using [filipo's code](https://pkg.go.dev/filippo.io/edwards25519)

### Origin Document

We are interested in *somewhat* standardizing the cryptographic conversion logic that converts from ed22519 to Curve25519.

I was further validated by finding an existing proposal to add this functionality to go’s standard cryptographic library in this [issue](https://github.com/golang/go/issues/20504)

#### Context

A primer on the matter is available in this [blogpost](https://blog.filippo.io/using-ed25519-keys-for-encryption) written by this [dude](https://twitter.com/FiloSottile?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1129786275924516864%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwords.filippo.io%2Fusing-ed25519-keys-for-encryption%2F) who happens to be a security research with Go’s team.

Takeaways:

- Edwards Curve (ed25519) and Montgomery’s curve (curve25519) are birationally equivalent
- (x,y) are usually referring to points on Edward’s curve, while (u, v) refers to points Montgomery in crypto nomenclature
- Since they are linked, RFC 7748 conveniently [provides](https://tools.ietf.org/html/rfc7748#page-5) the formulas to map `(x, y)` Ed25519 Edwards points to `(u, v)` Curve25519 Montgomery points and vice versa:
    
    ```jsx
    (u, v) = ((1+y)/(1-y), sqrt(-486664)*u/x)
    (x, y) = (sqrt(-486664)*u/v, (u-1)/(u+1))
    ```
    
- Ed25519 public keys are encoded as a Y coordinate and a "sign" bit in place of the full x coordinate.
    - This means that for each X25519 public key, there are two possible secret scalars (`k` and `-k`) and two equivalent Ed25519 public keys (with sign bit 0 and 1, also said to be one the negative of the other).
        - Meaning, one ed25519 public key → one x25519

### Deliverables

- [ ] Drop-in replacement standardized library for the custom conversion code present in `shared/crypto/mont.go` using the standardized Mathematical cryptographic operations from [filipo's code](https://pkg.go.dev/filippo.io/edwards25519)

### Owners
@derrandz

**Comment by Olshansk** [comment]
Closing for housekeeping but may reopen in the future.
