### ISSUE TITLE
[P2P] Add mechanism to handle large messages

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#70]
### Objective

An excerpt from the protobuf's documentation (_techniques section_)

> 
> 💡 **Streaming Multiple Messages**
> 
> If you want to write multiple messages to a single file or stream, it is up to you to keep track of where one message ends and the next begins. The Protocol Buffer wire format is not self-delimiting, so protocol buffer parsers cannot determine where a message ends on their own. The easiest way to solve this problem is **to write the size of each message before you write the message itself. When you read the messages back in, you read the size, then read the bytes into a separate buffer, then parse from that buffer.

Also from their website, same section:

> Protocol Buffers are not designed to handle large messages. As a general rule of thumb, if you are dealing in messages larger than a megabyte each, it may be time to consider an alternate strategy.

### Origin Document

With a maximal block size of 4MB, we need to be able to deliver such large messages. P2P has to put in place validation mechanisms to allow it to accept or decline a received payload depending on its size to avoid bandwidth consumption attacks and network congestions overall.

In order for us to achieve such behavior, we need ways to peak into the payload's metadata such as size before we engage in parsing it.

Protobuff does not provide such random access capability and requires that memory be allocated and for the message to be parsed before peaking into it.

### Deliverables

- [ ] A wire-byte level protocol to ensure the splitting, sequencing and streaming of large messages.

### Owners
@derrandz

**Comment by derrandz** [comment]
Close if #55 #57 alleviate the issue.

**Comment by Olshansk** [comment]
Closing this out due to the scope of the issue. We will likely need to cross this again in the future and will handle it then.

@derrandz If you think we should keep this open, please let us know.
