### ISSUE TITLE
[WIP][Utility][Document] Servicer protocol reward accumulation & distribution interface

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#714]
## Objective

Design an interface for Servicer protocol reward accumulation and distribution in the utility module of the Pocket Network. The interface should facilitate reward distribution based on volume estimation, salary eligibility, and other relevant parameters.

## Origin Document

[V1 Utility Specification - Salary Eligibility & Distribution
](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#325-salary-eligibility--distribution)

## Goals

- Design an interface to handle reward distribution for Servicers
- Design mechanisms for salary eligibility and distribution 
- Ensure proper integration with other aspects of utility, such as Fishermen, GeoZones, and RelayChains

## Deliverable

- [ ] Design an interface for Servicer protocol reward accumulation and distribution that includes:
   - [ ] A method for handling reward distribution based on volume estimation
   - [ ] A method for salary eligibility and distribution based on ReportCard scores

## Non-goals / Non-deliverables

- Implementing the interface or any of its components

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Closing this out in exchange for the process being put together in #733.
