### ISSUE TITLE
[WIP][Utility][Document] Servicer protocol interface for test scores & report cards protobuf definitions

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#715]
## Objective

Design a Servicer protocol interface for test scores and report cards protobuf definitions. This interface should handle the storage and management of test scores and report cards for Servicers.

## Origin Document

[V1 Utility Specification - Report Cards & Test Scores
](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#323-report-cards--test-scores)

## Goals

- Design an interface for handling Servicer test scores and report cards protobuf definitions
- Enable the storage and management of Servicer test scores and report cards
- Ensure proper integration with the Servicer protocol 

## Deliverable

- [ ] Design an interface for Servicer test scores and report cards protobuf definitions
- [ ] Define methods for handling test scores, including collection, storage, and retrieval
- [ ] Define methods for managing report cards, including aggregation, storage, and retrieval

## Non-goals / Non-deliverables

- Implementing the interface or any of its components

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Closing this out in exchange for the process being put together in #733.
