### ISSUE TITLE
[WIP][Utility] Implement Fisherman Servicer checks during a session a E2E Relay w/ signature verification but w/o rewards

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#717]
## Objective

Implement the Fisherman Servicer checks during a session for an end-to-end (E2E) relay system with signature verification but without rewards. The checks should include monitoring and sampling of Servicers during active sessions, ensuring a fair assessment across all Servicers.

## Origin Document

[V1 Utility Specification - Sampling Protocol
](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#333-sampling-protocol)

## Goals

- Implement Fisherman Servicer checks during a session for an E2E relay system
- Monitor and sample Servicers during active sessions according to the Sampling Protocol
- Collect data on Servicer performance, including availability, latency, and data consistency
- Implement incognito sampling using Ring Signatures to prevent Servicer bias

## Deliverable

- [ ]  Implement Fisherman Servicer checks for an E2E relay system during a session
- [ ] Implement the Sampling Protocol to monitor and sample Servicers during active sessions
- [ ] Collect data on Servicer performance, including availability, latency, and data consistency
- [ ] Implement incognito sampling using Ring Signatures to ensure fairness in Servicer assessments

## Non-goals / Non-deliverables

- Implementing rewards for Servicers or Fisherman (handled in separate tickets)

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
Confirm if ring signatures are in scope for this ticket

**Comment by Olshansk** [comment]
Closing this out in exchange for the process being put together in #733.
