### ISSUE TITLE
[Infrastructure] localnet config for full nodes

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#719]
## Objective

Create a localnet configuration for full nodes, ensuring the ability to scale up and distinguish between validators and full nodes, and preventing the cluster manager from staking when increasing the number of full nodes.

## Origin Document

There is a need to deploy full nodes on the network, which does not act in the pacemaker lifecycle (i.e., voting on blocks) but only downloads and applies them. To enable this, a localnet configuration should be created for full nodes, allowing for easy scaling and differentiation between validators and full nodes. See the [full conversation here](https://discord.com/channels/824324475256438814/1006230632285868063/1100900789096038431).

## Goals

- Create and integrate a localnet configuration for full nodes in Tilt, enabling easy scaling that seamlessly integrates with the existing validator setup
- Implement a solution to clearly differentiate between validators and full nodes
- Prevent staking operations when increasing the number of full nodes

## Deliverable

- [ ] Implement a scalable localnet configuration for full nodes in Tilt
- [ ] Implement an environment variable or another appropriate method to distinguish between validator and full node roles within the network
- [ ] Modify the cluster manager to recognize and handle full nodes in addition to validators. Specifically, ensure that the cluster manager does not perform staking operations when scaling up the number of full nodes in the network

## Non-goals / Non-deliverables

- Ensuring full functionality of non-staked actors
- Implementing any consensus module changes related to full nodes

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by jessicadaugherty** [comment]
Ready for review @okdas @Olshansk

**Comment by okdas** [comment]
@Olshansk considering full nodes do not participate in consensus, I don't believe we need to add a new actor in protobuf: https://github.com/pokt-network/pocket/blob/main/shared/core/types/proto/actor.proto#L7

Please let me know if you think otherwise.

**Comment by Olshansk** [comment]
> @Olshansk considering full nodes do not participate in consensus, I don't believe we need to add a new actor in protobuf: [`main`/shared/core/types/proto/actor.proto#L7](https://github.com/pokt-network/pocket/blob/main/shared/core/types/proto/actor.proto?rgh-link-date=2023-05-03T23%3A00%3A53Z#L7)
> 
> Please let me know if you think otherwise.

You are correct

**Comment by jessicadaugherty** [comment]
@okdas the “RPC node” should be changed to a “full node” (i.e. dispatched) instead of a validator after changes are merged.
