### ISSUE TITLE
[SPIKE][Utility] Stake ownership user flows

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#751]
## Objective

Investigate and compare stake ownership user flows for custodial and non-custodial staking, and recommend future improvements to these flows.

## Origin Document

TODO: Need to reference the existing flows in v0 as a reference / starting point for the origin document.

V0 staking [CLI documentation](https://github.com/pokt-network/pocket-core/blob/staging/doc/specs/cli/node.md)

V0 staking [user documentation](https://docs.pokt.network/node/staking/) 

V0 3P staking [user guide](https://docs.pokt.network/node/trustlessstaking/)

## Goals

- Analyze stake ownership user flows for both custodial and non-custodial staking
- Highlight the advantages and disadvantages of each approach in terms of user experience, security, and control
- Propose recommendations for future improvements to stake ownership user flows for both custodial and non-custodial staking

## Deliverable

- [ ] Comprehensive comparison document highlighting the key differences between custodial and non-custodial staking user flows
- [ ] Detailed analysis of stake ownership user flows for both custodial and non-custodial staking, including diagrams and flowcharts
- [ ] Assessment of the advantages and disadvantages of each approach in terms of user experience, security, and control
- [ ] Future improvement proposals for stake ownership user flows in both custodial and non-custodial staking, taking into account user experience, security, and control aspects

## Non-goals / Non-deliverables

 - Implementation of any staking mechanism or user flow

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
TODO: Need to reference the existing flows in v0 as a reference / starting point for the origin document.

**Comment by jessicadaugherty** [comment]
Are these sufficient or too simplified @Olshansk?

![Image](https://github.com/pokt-network/pocket/assets/55156619/8abe4cd7-6ce5-456a-a364-f989de6f44f2)
![Image](https://github.com/pokt-network/pocket/assets/55156619/61980659-f6ee-499b-80bb-57d4a1424ca8)

**Comment by Olshansk** [comment]
> @Olshansk? Also added in CLI/user docs to the origin doc section.

Great!

> We don't have any sort of visual representation like this I can find elsewhere. Are these sufficient or too simplified 

Ty. This is a good starting point
