### ISSUE TITLE
[Automation] CI for pushed / merged branches

### ISSUE THREAD

**Issue by okdas** [pokt-network/pocket#78]
# Objective
We've identified a need in a CI solution as a first step of building infrastructure and automation for pocket v1, as everything else is going to depend on that being done first.

# Origin Document
TBD, some rough notes for the next steps included in the onboarding doc: https://www.notion.so/Infrastructure-Dmitry-Onboarding-d7af22f439a74104892bec35d92651b7

# Goals / Deliverables
- [ ] Automatically running unit / integration tests
- [x] Automated artifact creation
   - [x] Docker image
      - [x] Debug/Development image with delve, troubleshooting CLI tools, etc.
      - [x] Production image that only includes binary and very necessary tools (if any)
  - [x] Support multiple architectures (amd64, arm64)
  - [x] Investigate if we can support ubuntu/alpine (musl) based images

## Non-goals
- List of goals that this issue won't address

Owner: @okdas
Co-Owners: TBD
Deliverables: TBD

**Comment by Olshansk** [comment]
@okdas I believe this is done, correct?

If so, I think the only missing piece is documentation. E.g. Adding a README with a link of where the images are being pushed would really help.

**Comment by okdas** [comment]
@Olshansk this is done, correct, and some (though not very deep) documentation pushed as well: https://github.com/pokt-network/pocket/tree/main/docs/build
