### ISSUE TITLE
[Utility] Cache session data in client

### ISSUE THREAD

**Issue by adshmh** [pokt-network/pocket#791]
## Objective

Cache sessions client-side

## Origin Document
#754 and #778 

Cache the retrieved sessions client-side.

## Goals

- Avoid repeatedly fetching sessions that have already been retrieved.

## Deliverable

- [ ] PR that adds caching of sessions on client side
- [ ] PR that uses the cached sessions in the new servicer sub-command

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
- [ ] **k8s LocalNet**: verify a `k8s LocalNet` is still functioning correctly by following the instructions [here](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md)

---

**Creator**: @adshmh

**Comment by adshmh** [comment]
@Olshansk would appreciate a bit more context on the expectations here. More specifically, does this make sense?
1. Client checks the local cache for a stored session (on permanent storage, to allow sharing the session between multiple invocations of the client)
2. If a session is found --> verify against the current height
3. If a session is not found or the stored session has expired (i.e. does not match the current height): fetch the current session and store in cache (permanent storage)

Also, wondering if it makes sense to cache and store older sessions: if there is a need on client-side to access old sessions this would make sense, but I can't think of one right now.

**Comment by Olshansk** [comment]
I recently had to do this in v0 `tx-bot` and hacked (keyword hacked) it together. See https://github.com/pokt-network/tx-bot/blob/main/rpc/req.go#L93

> Client checks the local cache for a stored session (on permanent storage, to allow sharing the session between multiple invocations of the client)

What is `permanent storage` here? If it's just something simple like a text/binary file under `/tmp`, then 👍 

> If a session is found --> verify against the current height

If validation means "check if session is still useful given the nodes", then 👍 

Otherwise, please provide more details.


> If a session is not found or the stored session has expired (i.e. does not match the current height): fetch the current session and store in cache (permanent storage)

👍 

> Also, wondering if it makes sense to cache and store older sessions: if there is a need on client-side to access old sessions this would make sense, but I can't think of one right now.

Can't think of any reasons right now. If it's important, it'll come back up.
