### ISSUE TITLE
[SPIKE][Utility] E2E Feature Flag Scoping & Definition

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#822]
## Objective

Scope out the E2E Feature Flag M3 work.

## Origin Document

The [E2E Feature Flag Item](https://github.com/pokt-network/pocket/blob/main/utility/doc/E2E_FEATURE_LIST.md#f-e2e-feature-flags-) is a high priority feature that blocks the deployment of M3.

With the help of @0xBigBoss, we started scoping it out [here](https://www.notion.so/pocketnetwork/DRAFT-Pocket-Tech-Spec-Block-height-activated-feature-flags-64a7a70230724994bf85edab206b1c0b?pvs=4) but there is more work ahead.

![Screenshot 2023-06-13 at 10 01 15 PM](https://github.com/pokt-network/pocket/assets/1892194/07aa6e01-0211-4ff1-be50-2a8d9e2c6a96)

![Screenshot 2023-06-13 at 12 00 30 PM](https://github.com/pokt-network/pocket/assets/1892194/34500f06-b4ba-49e7-b48e-487259191b87)

## Goals

- Scope out the work needed to implement feature flags, governance params and protocol upgrades

## Deliverable

- [ ] An E2E Feature Path template as outlined [here](https://github.com/pokt-network/pocket/blob/main/utility/doc/E2E_FEATURE_PATH_TEMPLATE.md#scope-feature) that will use to drive the prototyping and implementation of the feature

## Non-goals / Non-deliverables

- Anything related to the implementation of the feature

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
- [ ] **k8s LocalNet**: verify a `k8s LocalNet` is still functioning correctly by following the instructions [here](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md)

---

**Creator**: @Olshansk 
**Co-Owners**: @0xBigBoss

**Comment by Olshansk** [comment]
This work is being led by @0xBigBoss.

The initial design can be found here: https://www.notion.so/pocketnetwork/0-1-0-Pocket-Tech-Spec-Block-height-activated-feature-flags-64a7a70230724994bf85edab206b1c0b?pvs=4

**Comment by Olshansk** [comment]
@0xBigBoss I've moved this from iteration19 to iteration20 as we did not complete it in time.

I know you'll be partially OOO this week, but do you think we can convert the notion page into markdown and merge it into main by mid next week?

**Comment by 0xBigBoss** [comment]
@Olshansk I have the scope feature issues opened. wdym merge into main? do you mean the mvc deliverables from #882 and #879 ?

**Comment by Olshansk** [comment]
> wdym merge into main

Ignore what I said :)

Reviewed both issues you scoped out and LGTM. Left a comment with some follow-ups on one of them, but nothing blocking the work! LFG

**Comment by Olshansk** [comment]
Closing this ticket out per the work done by @0xBigBoss  in #882 and #879. Moving future work/conversations there
