### ISSUE TITLE
[LOCALNET][K8s] Publish Servicers Host and Port as environment variables

### ISSUE THREAD

**Issue by adshmh** [pokt-network/pocket#823]
## Objective

Easily accessing servicers in LocalNet.

## Origin Document

#754 

## Goals

- Any services in the LocalNet is accessible through a hostname/port combination, similar to validators.

## Deliverable

- [ ] Updated LocalNet configuration.

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)
- [ ] **k8s LocalNet**: verify a `k8s LocalNet` is still functioning correctly by following the instructions [here](https://github.com/pokt-network/pocket/blob/main/build/localnet/README.md)

---

**Creator**: @adshmh 
**Co-Owners**: @okdas

**Comment by okdas** [comment]
@adshmh, we already have the following services:

* `pocket-$(actor_name)` - has `50832` (RPC) and `9000` (metrics) ports. It resolves to a random healthy actor.
* `$(actor_name)-$(number)-pocket` - in addition to RPC and metrics, it exposes the `42069` (consensus) port.

Please let me know if I misunderstood the objective. 

<img width="362" alt="image" src="https://github.com/pokt-network/pocket/assets/4950477/70294b95-0405-46e5-8c20-856cd1a8d8de">

**Comment by Olshansk** [comment]
@adshmh Wanted to bump @okdas's comment above.

**Comment by adshmh** [comment]
> @adshmh Wanted to bump @okdas's comment above.

Thanks for the reminder. Will be doing a few tests shortly. I will update the results here.

**Comment by adshmh** [comment]
> @adshmh, we already have the following services:
> 
>     * `pocket-$(actor_name)` - has `50832` (RPC) and `9000` (metrics) ports. It resolves to a random healthy actor.
> 
>     * `$(actor_name)-$(number)-pocket` - in addition to RPC and metrics, it exposes the `42069` (consensus) port.
> 
> 
> Please let me know if I misunderstood the objective. Otherwise, I think we can close this.

@okdas thank you for the clarification. The servicer name resolves in my LocalNet tests. I think this can be closed.
