### ISSUE TITLE
[Tooling] CHANGELOG and Version Bump PreCommit Hook

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#93]
### Description

The v1 codebase is required to document all important changes in a `CHANGELOG.md` at the root of the repository and module specific `CHANGELOG.md` if the changes impacted the module in-question. In addition to that, the version should be bumped accordingly.

This issue is a perfect starter task for community contributions.

## Origin Document

This issue was created as a starter task for community contribution, as suggested per in the following [conversation](https://github.com/pokt-network/pocket/pull/80#discussion_r898622625)

## Goals

- [ ] Add pre-commit logic to validate if CHANGELOGs and the version were updated accordingly before commit
- [ ] Allow this to be disable locally
- [ ] Configure CI to always run this validation before merge of PRs

## Non-Goals

- [ ] Adding CI/CD to the V1 Codebase
- [ ] Automating the population of the CHANGELOG based on git-diff results

## Maintainers
Creator: @derrandz

**Comment by Olshansk** [comment]
@derrandz Could you link to some examples of where the changelogs are right now for those who are new to the code base?

**Comment by Olshansk** [comment]
For anyone who comes by this issue, I recently found this diff that removed this feature (which we actually want here): https://github.com/celestiaorg/smt/pull/68/files

GitOps is an alternative tool we can use in addition / instead of a PreCommit hook.

Disclaimer: I did not do in-depth research into this.
