### ISSUE TITLE
[Telemetry] Add support for telemetry clients other than prometheus

### ISSUE THREAD

**Issue by derrandz** [pokt-network/pocket#99]
## Description

Provide support for multiple telemetry clients.

## Origin Document

> Could you create a starter task github issue that says "Add support for telemetry clients other than prometheus" with links or references to these code examples?

> I think it's "easy enough" and eye-catchy enough that a lot of infra folks would look at it when they try to get onboarded onto the codebase

_Originally posted by @Olshansk in https://github.com/pokt-network/pocket/pull/95#discussion_r906863195_

## Changes

In `shared/telemetry/module.go`, specifically in the `Create` function, we would like to:

1. Provide support for multiple telemetry clients by implementing a switch statement that creates the correct telemetry client provided in the config.

1. Implement this new client(s)

## Owners

N/A (Open for picking)

**Comment by Olshansk** [comment]
Going to close this out as it is not going to be a requirement in the near future and will be reopened (and require a lot of discussion) when the time comes.
